// ==UserScript==
// @name           Rycochet's Castle Age Golem
// @namespace      golem
// @description    Auto player for castle age game
// @version        10
// @include        http*://apps.*facebook.com/castle_age/*
// @require        http://cloutman.com/jquery-latest.min.js
// @require        http://cloutman.com/jquery-ui-latest.min.js
// ==/UserScript==
// -- @include        http://www.facebook.com/common/error.html
// -- @include        http://www.facebook.com/reqs.php#confirm_46755028429_0
// -- @include        http://www.facebook.com/home.php
// -- @include        http://www.facebook.com/home.php*filter=app_46755028429*
var debug=true,VERSION=10,APP="46755028429",PREFIX="golem"+APP+"_",userID=unsafeWindow.Env.user,script_started=Date.now();
function main(){if(!Page.loading()&&!$("#secret_golem_check").length){if(!$("#app"+APP+"_nvbar_div_end").length){Page.reload();return}$("#app"+APP+"_nvbar_div_end").append('<br id="secret_golem_check" style="display:none"/>');Page.identify();for(var a in Workers)Workers[a].priv_parse=Workers[a].pages&&(Workers[a].pages=="*"||Page.page&&Workers[a].pages.indexOf(Page.page)>=0)&&Workers[a].parse?Workers[a].parse(false):false;Settings.Save("data");for(a in Workers)Workers[a].priv_parse&&Workers[a].parse(true)}Queue.run()}
$(document).ready(function(){Page.identify();Settings.Load("data");Settings.Load("option");if(window.location.href.indexOf("castle_age")>=0){for(var a in Workers)Workers[a].onload&&Workers[a].onload();main();window.setInterval(function(){main()},1E3)}});
function Panel(a){this.name=a;this.show=$('<div style="font-size:smaller;padding:12px;"></div>');this.options=function(b){b=b||{};b.before=b.before||"";b.after=b.after||"";b.suffix=b.suffix||"";b.between=b.between||"to";b.size=b.size||7;b.min=b.min||0;b.max=b.max||100;return b};this.checkbox=function(b,c,d){var e=WorkerByName(this.name).option[b]||false;b=PREFIX+this.name+"_"+b;c=c.replace(" ","&nbsp;");d=this.options(d);$(this.show).append('<div style="clear:both"><span style="float:left;">'+c+'</span><span style="float:right;text-align:right">'+
d.before+'<input type="checkbox" id="'+b+'" '+(e?" checked":"")+">"+d.after+"</span></div>");return b};this.text=function(b,c,d){var e=WorkerByName(this.name).option[b]||"";b=PREFIX+this.name+"_"+b;c=c.replace(" ","&nbsp;");d=this.options(d);$(this.show).append('<div style="clear:both"><span style="float:left;">'+c+'</span><span style="float:right;text-align:right">'+d.before+'<input type="text" id="'+b+'" size="'+d.size+'" value="'+e+'">'+d.after+"</span></div>");return b};this.select=function(b,
c,d,e){var f=WorkerByName(this.name).option[b]||null;b=PREFIX+this.name+"_"+b;c=c.replace(" ","&nbsp;");var h=[];e=this.options(e);d||(d=[]);if(typeof d=="number"){var l=Divisor(d),j=d;d=[];for(var g=0;g<=j;g+=l)d.push(g)}for(g in d)h[g]=typeof d[g]=="object"?'<option value="'+d[g][0]+'"'+(f==d[g][0]?" selected":"")+">"+d[g][0]+" ("+d[g][1]+e.suffix+")</option>":'<option value="'+d[g]+'"'+(f==d[g]?" selected":"")+">"+d[g]+e.suffix+"</option>";$(this.show).append('<div style="clear:both"><span style="float:left;">'+
c+'</span><span style="float:right;text-align:right">'+e.before+'<select id="'+b+'">'+h.join("")+"</select>"+e.after+"</span></div>");return b};this.multiple=function(b,c,d,e){var f=WorkerByName(this.name).option[b]||[];b=PREFIX+this.name+"_"+b;c=c.replace(" ","&nbsp;");var h=[],l=[];e=this.options(e);d||(d=[]);for(var j in d)h[j]=typeof d[j]=="object"?'<option value="'+d[j][0]+'">'+d[j][0]+" ("+d[j][1]+")</option>":'<option value="'+d[j]+'">'+d[j]+"</option>";for(j in f)l[j]='<option value="'+f[j]+
'">'+f[j]+"</option>";c=$('<div style="clear:both"><span style="float:left;">'+c+'</span><span style="float:right;text-align:right"><select style="width:100%" class="golem_multiple" multiple id="'+b+'">'+l.join("")+'</select><br><select class="golem_select">'+h.join("")+'</select><input type="button" class="golem_addselect" value="Add" /><input type="button" class="golem_delselect" value="Del" /></span></div>');$("input.golem_addselect",c).click(function(){$("select.golem_multiple",$(this).parent()).append("<option>"+
$("select.golem_select",$(this).parent()).val()+"</option>");Config.updateOptions()});$("input.golem_delselect",c).click(function(){$("select.golem_multiple option[selected=true]",$(this).parent()).each(function(g,i){$(i).remove()});Config.updateOptions()});$(this.show).append(c);return b};this.range=function(b,c,d){var e=WorkerByName(this.name).option[b+"_min"]||0,f=WorkerByName(this.name).option[b+"_max"]||100;b=PREFIX+this.name+"_"+b;c=c.replace(" ","&nbsp;");d=this.options(d);var h=Divisor(d.max-
d.min),l=[],j=[];if(typeof e=="number")e-=e%h;if(typeof f=="number")f-=f%h;for(var g=d.min;g<=d.max;g+=h){l.push('<option value="'+g+'"'+(e==g?" selected":"")+">"+g+"</option>");j.push('<option value="'+g+'"'+(f==g?" selected":"")+">"+g+"</option>")}l.unshift('<option value="None"'+(e=="None"?" selected":"")+">None</option>");j.push('<option value="All"'+(f=="All"?" selected":"")+">All</option>");$(this.show).append('<div style="clear:both"><span style="float:left;">'+c+'</span><span style="float:right;text-align:right">'+
d.before+'<select id="'+b+'_min">'+l.join("")+"</select> "+d.between+' <select id="'+b+'_max">'+j.join("")+"</select>"+d.after+"</span></div>");return b};this.general=function(b,c,d){b=PREFIX+this.name+"_"+b;c=c.replace(" ","&nbsp;");$(this.show).append('<div style="clear:both"><span style="float:left;">'+c+'</span><span style="float:right;"><select id="'+b+'" class="golem_generals" alt="'+d+'"></select></span></div>')};this.div=function(b,c){b=PREFIX+this.name+"_"+b;$(this.show).append('<div id="'+
b+'" style="clear:both">'+c+"<br /><br /></div>");return b};this.info=function(b,c,d){if(c&&d){c=PREFIX+this.name+"_"+c;d=d.replace(" ","&nbsp;");$(this.show).append('<div style="clear:both"><span style="float:left;">'+d+'</span><span style="float:right;" id="'+c+'">'+b+"</span></div>");return c}else $(this.show).append('<div style="clear:both">'+b+"<br /><br /></div>")}}
var Settings={SetValue:function(a,b){switch(typeof b){case "boolean":case "number":return GM_setValue(a,b);case "string":return GM_setValue(a,'"'+b+'"');case "array":case "object":return GM_setValue(a,b.toSource());default:GM_debug("Unknown variable type: "+a)}return null},GetValue:function(a,b){b=GM_getValue(a,b);if(typeof b==="string")if(b.charAt(0)==='"')b=b.replace(/^"|"$/g,"");else if(b.charAt(0)==="("||b.charAt(0)==="[")b=eval(b);return b},Save:function(a,b){if(typeof a==="object"){b=a;a="data"}if(a!==
"data"&&a!=="option")a="data";if(b&&b[a])Settings.SetValue(a+"."+b.name,b[a]);else for(var c in Workers)Workers[c][a]&&Settings.SetValue(a+"."+Workers[c].name,Workers[c][a])},Load:function(a,b){if(typeof a==="object"){b=a;a="data"}if(a!=="data"&&a!=="option")a="data";if(b&&b[a])b[a]=Settings.GetValue(a+"."+b.name,b[a]);else for(var c in Workers)if(Workers[c][a])Workers[c][a]=Settings.GetValue(a+"."+Workers[c].name,Workers[c][a])}};
String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")};String.prototype.filepart=function(){var a=this.lastIndexOf("/");if(a>=0)return this.substr(a+1);return this};String.prototype.pathpart=function(){var a=this.lastIndexOf("/");if(a>=0)return this.substr(0,a+1);return this};String.prototype.regex=function(a){a=this.match(a);var b;if(a){a.shift();for(b=0;b<a.length;b++)if(a[b]&&a[b].search(/^[-+]?[0-9]+\.?[0-9]*$/)>=0)a[b]=parseFloat(a[b]);if(a.length===1)return a[0]}return a};
String.prototype.toNumber=function(){return parseFloat(this)};String.prototype.parseTimer=function(){var a=this.split(":"),b=0,c;for(c=0;c<a.length;c++)b=b*60+parseInt(a[c],10);if(isNaN(b))b=9999;return b};if(typeof GM_debug==="undefined")GM_debug=function(a){debug&&GM_log(a)};
var WorkerByName=function(a){for(var b in Workers)if(Workers[b].name===a)return Workers[b];return null},WorkerById=function(a){for(var b in Workers)if(Workers[b].priv_id===a)return Workers[b];return null},Divisor=function(a){var b=a,c=1;if(b<20)return 1;for(;b>100;){b/=10;c*=10}if(a/c>40)c*=5;else if(a/c>20)c*=2.5;return c},length=function(a){var b=0,c;if(typeof a==="object")for(c in a)b++;else if(typeof a==="array")b=a.length;return b},unique=function(a){var b={},c,d=a.length,e=[];for(c=0;c<d;c++)b[a[c]]=
a[c];for(c in b)e.push(b[c]);return e},addCommas=function(a){a=a.toString();for(var b=/(-?[0-9]+)([0-9]{3})/;b.test(a);)a=a.replace(b,"$1,$2");return a},getAttDef=function(a,b,c,d,e){var f=[],h=0,l=0,j=c=="att"?"def":"att",g;for(g in a)b(f,g,a);f.sort(function(i,m){return a[m][c]+0.7*a[m][j]-(a[i][c]+0.7*a[i][j])});for(g=0;g<f.length;g++){b=typeof a[f[g]].own==="number"?a[f[g]].own:1;if(e)if(Math.min(d,b)>0){GM_debug("Using: "+Math.min(d,b)+" x "+f[g]+" = "+a[f[g]].toSource());if(!a[f[g]].use)a[f[g]].use=
{};a[f[g]].use[e+"_"+c]=Math.min(d,b)}else if(a[f[g]].use){delete a[f[g]].use[e+"_"+c];length(a[f[g]].use)||delete a[f[g]].use}if(d<=0)break;b=Math.min(d,b);h+=b*a[f[g]].att;l+=b*a[f[g]].def;d-=b}return(c=="att"?h:0.7*h)+(c=="def"?l:0.7*l)},Workers=[];function Worker(a,b){this.id=Workers.push(this);this.name=a;this.pages=b;this.unsortable=false;this.data={};this.option={};this.work=this.parse=this.display=this.onload=null;this.priv_parse=false;this.priv_since=0;this.priv_id=null}
Alchemy=new Worker("Alchemy","keep_alchemy");Alchemy.onload=function(){if(!Alchemy.data.ingredients)Alchemy.data.ingredients={};if(!Alchemy.data.recipe)Alchemy.data.recipe={}};
Alchemy.parse=function(){var a=Alchemy.data.ingredients={},b=Alchemy.data.recipe={};$("div.ingredientUnit").each(function(c,d){c=$("img",d).attr("src").filepart();a[c]=$(d).text().regex(/x([0-9]+)/)});$("div.alchemyQuestBack,div.alchemyRecipeBack,div.alchemyRecipeBackMonster").each(function(c,d){var e={};c=$("div.recipeTitle",d).text().trim().replace("RECIPES: ","");if(c.indexOf(" (")>0)c=c.substr(0,c.indexOf(" ("));e.type=$(d).hasClass("alchemyQuestBack")?"Quest":$(d).hasClass("alchemyRecipeBack")?
"Recipe":$(d).hasClass("alchemyRecipeBackMonster")?"Summons":"wtf";e.ingredients={};$("div.recipeImgContainer",d).parent().each(function(f,h){f=$("img",h).attr("src").filepart();e.ingredients[f]=$(h).text().regex(/x([0-9]+)/)||1});b[c]=e})};Alchemy.display=function(){var a=new Panel(this.name);a.checkbox("perform","Automatically Perform");a.checkbox("hearts","Use Battle Hearts");return a.show};
Alchemy.work=function(a){if(!length(Alchemy.data.ingredients)){if(!a)return true;if(!Page.to("keep_alchemy"))return true}if(!Alchemy.option.perform)return false;var b=null,c=Alchemy.data.recipe;for(var d in c)if(c[d].type=="Recipe"){b=d;for(var e in c[d].ingredients)if(!Alchemy.option.hearts&&e=="raid_hearts.gif"||c[d].ingredients[e]>(Alchemy.data.ingredients[e]||0)){b=null;break}if(b)break}if(!b)return false;if(!a)return true;if(!Page.to("keep_alchemy"))return true;GM_debug("Alchemy: Perform - "+
b);$("div.alchemyRecipeBack").each(function(f,h){if($("div.recipeTitle",h).text().indexOf(b)>=0){Page.click($('input[type="image"]',h));return true}});return true};Bank=new Worker("Bank");Bank.data=null;Bank.onload=function(){if(!Bank.option.above||isNaN(Bank.option.above))Bank.option.above=0;if(!Bank.option.hand||isNaN(Bank.option.hand))Bank.option.hand=0;if(!Bank.option.keep||isNaN(Bank.option.keep))Bank.option.keep=0};
Bank.display=function(){var a=new Panel(this.name);a.checkbox("general","Use Best General:");a.text("above","Bank Above:");a.text("hand","Keep in Cash:");a.text("keep","Keep in Bank:");return a.show};Bank.work=function(a){if(Player.data.cash<Bank.option.above)return false;if(!a)return true;if(!Bank.stash(Player.data.cash-Math.min(Bank.option.above,Bank.option.hand)))return true;return false};
Bank.stash=function(a){if(!a||!Player.data.cash)return true;if(Bank.option.general&&!Generals.to("Aeris"))return false;if(!Page.to("keep_stats"))return false;$('input[name="stash_gold"]').val(Math.min(Player.data.cash,a));Page.click('input[value="Stash"]');return true};Bank.retrieve=function(a){a-=Player.data.gold;if(a<=0)return true;if(Player.data.bank-Bank.option.keep<a)return true;if(!Page.to("keep_stats"))return false;$('input[name="get_gold"]').val(a);Page.click('input[value="Retrieve"]');return true};
Bank.worth=function(){return Player.data.cash+Math.max(0,Player.data.bank-Bank.option.keep)};Battle=new Worker("Battle","battle_battle battle_rank");Battle.onload=function(){if(!Battle.data.user)Battle.data.user={};if(!Battle.data.rank)Battle.data.rank={};if(!Battle.data.points)Battle.data.points=[];if(!Battle.option.type)Battle.option.type="Invade"};
Battle.parse=function(a){if(a)return false;if(Page.page=="battle_battle"){var b=Battle.data.user;for(var c in b)Player.data.rank-b[c].rank>=5&&delete b[c];if(Battle.data.attacking){a=Battle.data.attacking;if($("div.results").text().match(/You cannot battle someone in your army/i))delete b[a];else if($("div.results").text().match(/Your opponent is dead or too weak/i))b[a].dead=Date.now();else if($('img[src*="battle_victory"]').length)if(b[a].win)b[a].win++;else b[a].win=1;else if($('img[src*="battle_defeat"]').length)if(b[a].loss)b[a].loss++;
else b[a].loss=1;Battle.data.attacking=null}Battle.data.points=$("#app"+APP+"_app_body table.layout table table").prev().text().replace(/[^0-9\/]/g,"").regex(/([0-9]+)\/10([0-9]+)\/10([0-9]+)\/10([0-9]+)\/10([0-9]+)\/10/);$("#app"+APP+"_app_body table.layout table table tr:even").each(function(d,e){d=$('img[uid!=""]',e).attr("uid");var f=$("td.bluelink",e).text().trim().regex(/Level ([0-9]+) (.*)/i);if(d&&f){b[d]||(b[d]={});b[d].name=$("a",e).text().trim();b[d].level=f[0];b[d].rank=Battle.rank(f[1]);
b[d].army=$("td.bluelink",e).next().text().regex(/([0-9]+)/);b[d].align=$('img[src*="graphics/symbol_"]',e).attr("src").regex(/symbol_([0-9])/i)}})}else if(Page.page=="battle_rank"){b=Battle.data.rank={0:{name:"Squire",points:0}};$('tr[height="23"]').each(function(d,e){d=$(e).text().regex(/Rank ([0-9]+) - (.*)\s*([0-9]+)/i);b[d[0]]={name:d[1],points:d[2]}})}return false};
Battle.display=function(){var a=new Panel(this.name);a.info("NOTE: Attacks at a loss up to 5 times more than a win");a.checkbox("general","Use Best General");a.select("type","Battle Type",["Invade","Duel"]);a.checkbox("points","Always Get Demi-Points");a.checkbox("monster","Fight Monsters First");return a.show};
Battle.work=function(a){if(!length(Battle.data.rank)){if(!a)return true;Page.to("battle_battlerank")}if(!length(Battle.data.points)){if(!a)return true;Page.to("battle_battle")}if(Player.data.health<=10||Queue.burn.stamina<1)return false;var b,c=[],d=[],e=Battle.data.user;if(Battle.option.points)for(b=0;b<Battle.data.points.length;b++)if(Battle.data.points[b]<10)c[b+1]=true;if((!Battle.option.points||!c.length)&&Battle.option.monster&&Monster.uid)return false;for(b in e)if(!(e[b].dead&&e[b].dead+18E5<
Date.now()))if(!((e[b].win||0)-(e[b].loss||0)<5))if(!Battle.option.points||!c.length||typeof c[e[b].align]!=="undefined")d.push(b);if(!d.length)return false;if(!a)return true;if(Battle.option.general&&!Generals.to(Generals.best(Battle.option.type)))return true;if(!Page.to("battle_battle"))return true;a=d[Math.floor(Math.random()*d.length)];GM_debug("Battle: Wanting to attack "+e[a].name+" ("+a+")");e=$('form input[alt="'+Battle.option.type+'"]').first().parents("form");if(!e.length){GM_log("Battle: Unable to find attack buttons, forcing reload");
Page.to("index");return false}Battle.data.attacking=a;$('input[name="target_id"]',e).attr("value",a);Page.click($('input[type="image"]',e));return true};Battle.rank=function(a){for(var b in Battle.data.rank)if(Battle.data.rank[b].name==a)return parseInt(b);return 0};Blessing=new Worker("Blessing","oracle_demipower");Blessing.which=["None","Energy","Attack","Defense","Health","Stamina"];
Blessing.parse=function(){var a=$("div.results");if(a.length){var b=a.text().regex(/Please come back in: ([0-9]+) hours and ([0-9]+) minutes/i);if(b&&b.length)Blessing.data.when=Date.now()+(b[0]*60+b[1]+1)*6E4;else if(a.text().match(/You have paid tribute to/i))Blessing.data.when=Date.now()+8646E4}return false};Blessing.display=function(){var a=new Panel(this.name);a.select("which","Which:",Blessing.which);return a.show};
Blessing.work=function(a){if(!Blessing.option.which||Blessing.option.which=="None")return false;if(Date.now()<=Blessing.data.when)return false;if(!a)return true;if(!Page.to("oracle_demipower"))return true;Page.click("#app"+APP+"_symbols_form_"+Blessing.which.indexOf(Blessing.option.which)+" input.imgButton");return false};var $configWindow=null;Config=new Worker("Config");Config.data=null;Config.option='({top:60,left:25,width:250,height:"auto",active:false})';Config.panel=null;
Config.onload=function(){$("head").append('<link rel="stylesheet" href="http://cloutman.com/css/base/jquery-ui.css" type="text/css" />');Config.panel=$('<div class="ui-widget-content" style="'+("top:"+Config.option.top+"px;left:"+Config.option.left+"px;width:"+Config.option.width+"px;height:auto;")+'padding:0;position:absolute;overflow:hidden;overflow-y:auto;"><div class="ui-widget-header" id="golem_title" style="padding:4px;cursor:move;overflow:hidden;">Castle Age Golem v'+VERSION+'</div><div id="golem_buttons" style="margin:4px;"></div><div id="golem_config" style="margin:4px;overflow:hidden;overflow-y:auto;"></div></div>');
$("#content").append(Config.panel);$(Config.panel).draggable({containment:"parent",handle:"#golem_title",stop:function(){Config.saveWindow()}}).resizable({containment:"parent",handles:"se",minWidth:100,resize:function(){$("#golem_config").height($(Config.panel).height()-$("#golem_config").position().top-8)},stop:function(){Config.saveWindow()}});var a=$("#golem_config");a.sortable({axis:"y"});for(var b in Workers)if(Workers[b].display){var c=Workers[b].display();if(c){Workers[b].priv_id="golem_panel_"+
Workers[b].name.toLowerCase().replace(/[^0-9a-z]/,"_");var d=$('<div id="'+Workers[b].priv_id+'"'+(Workers[b].unsortable?' class="golem_unsortable"':"")+' name="'+Workers[b].name+'"><h3><a>'+(Workers[b].unsortable?'<img "class="ui-icon ui-icon-locked" style="left:2em;width:16px;height:16px" />&nbsp;&nbsp;&nbsp;&nbsp;':"")+Workers[b].name+"</a></h3></div>");d.append(c);a.append(d)}}a.accordion({autoHeight:false,clearStyle:true,active:false,collapsible:true,header:"div > h3",change:function(){Config.saveWindow()}});
a.children(":not(.golem_unsortable)").draggable({connectToSortable:"#golem_config",axis:"y",distance:5,scroll:false,handle:"h3",helper:"clone",opacity:0.75,zIndex:100,refreshPositions:true,stop:function(){Config.updateOptions()}}).droppable({tolerance:"pointer",over:function(e,f){Config.getPlace($(this).attr("id"))<Config.getPlace($(f.draggable).attr("id"))?$(this).before(f.draggable):$(this).after(f.draggable)}});Generals.select();$("input ,textarea, select",a).change(function(){Config.updateOptions()})};
Config.saveWindow=function(){Config.option.top=$(Config.panel).offset().top;Config.option.left=$(Config.panel).offset().left;Config.option.width=$(Config.panel).width();Config.option.height=$(Config.panel).height();Config.option.active=$("#golem_config h3.ui-state-active").parent().attr("id");Settings.Save("option",Config)};
Config.updateOptions=function(){GM_debug("Options changed");var a={};Queue.option.queue=[];$("#golem_config > div").each(function(b,c){b=WorkerById($(c).attr("id")).name;a[b]||Queue.option.queue.push(b);a[b]=true});$("#golem_config :input").each(function(b,c){if($(c).attr("id"))if(b=$(c).attr("id").slice(PREFIX.length).regex(/([^_]*)_(.*)/i))if($(c).attr("type")=="checkbox")WorkerByName(b[0]).option[b[1]]=$(c).attr("checked");else{if($(c).attr("multiple")){var d=[];$("option",c).each(function(e,f){d.push($(f).text())})}else if((d=
$(c).val()||null)&&d.search(/[^0-9.]/))d=parseFloat(d);WorkerByName(b[0]).option[b[1]]=d}});Settings.Save("option")};Config.getPlace=function(a){var b=-1;$("#golem_config > div").each(function(c,d){if($(d).attr("id")==a&&b==-1)b=c});return b};Dashboard=new Worker("Dashboard","*");
Dashboard.parse=function(){if(!$("#golem_dashboard").length){$("#app"+APP+"_nvbar_nvl").css({width:"760px","padding-left":0,margin:"auto"});$('<div><div class="nvbar_start"></div><div class="nvbar_middle"><a id="golem_toggle_dash"><span class="hover_header">Dashboard</span></a></div><div class="nvbar_end"></div></div><div><div class="nvbar_start"></div><div class="nvbar_middle"><a id="golem_toggle_config"><span class="hover_header">Config</span></a></div><div class="nvbar_end"></div></div>').prependTo("#app"+APP+
"_nvbar_nvl > div:last-child");$('<div id="golem_dashboard" style="position:absolute;width:600px;height:185px;margin:0;border-left:1px solid black;border-right:1px solid black;padding4px;overflow:hidden;overflow-y:auto;background:white;z-index:1;">Dashboard...</div>').prependTo("#app"+APP+"_main_bn_container");$("#golem_toggle_dash").toggle(function(){$("#golem_dashboard").hide()},function(){$("#golem_dashboard").show()});$("#golem_toggle_config").toggle(function(){$("#golem_title").parent().hide()},
function(){$("#golem_title").parent().show()})}return false};Debug=new Worker("Debug");Debug.data=null;Debug.option=null;Debug.display=function(){if(!debug)return null;var a=$("<button>Debug</button>").button().click(function(){debug^=true;GM_log("Debug "+(debug?"on":"off"));$("span",this).css("text-decoration",debug?"none":"line-through")});$("#golem_buttons").append(a);return null};Generals=new Worker("General","heroes_generals");Generals.best_id=null;
Generals.onload=function(){if(!Generals.data)Generals.data={}};
Generals.parse=function(a){if(a){if(length(Town.data.invade)){i=Generals.data;for(var b in i){a=Player.data.attack+(i[b].skills.regex(/([+-]?[0-9]+) Player Attack/i)||0)+(i[b].skills.regex(/Increase Player Attack by ([0-9]+)/i)||0);var c=Player.data.defense+(i[b].skills.regex(/([+-]?[0-9]+) Player Defense/i)||0)+(i[b].skills.regex(/Increase Player Defense by ([0-9]+)/i)||0),d=i[b].skills.regex(/Increases? Army Limit to ([0-9]+)/i)||501,e=getAttDef(Generals.data,function(m,k){m.push(k)},"att",Math.floor(d/
5)),f=getAttDef(i,function(m,k){m.push(k)},"def",Math.floor(d/5));i[b].invade={att:Math.floor(Town.data.invade.attack+i[b].att+i[b].def*0.7+(a+c*0.7)*d+e),def:Math.floor(Town.data.invade.defend+i[b].def+i[b].att*0.7+(c+(i[b].skills.regex(/([-+]?[0-9]+) Defense when attacked/i)||0)+a*0.7)*d+f)};i[b].duel={att:Math.floor(Town.data.duel.attack+i[b].att+i[b].def*0.7+a+c*0.7),def:Math.floor(Town.data.duel.defend+i[b].def+i[b].att*0.7+c+a*0.7)}}var h=0,l=0,j=0,g=0;for(b in Generals.data){h=Math.max(h,Generals.data[b].invade.att);
l=Math.max(l,Generals.data[b].invade.def);j=Math.max(j,Generals.data[b].duel.att);g=Math.max(g,Generals.data[b].duel.def)}$("#app"+APP+"_generalContainerBox2 > div > div.generalSmallContainer2").each(function(m,k){m=$(k).children();k=m.eq(0).text().trim();m.eq(1).prepend('<div style="position:absolute;margin-left:8px;margin-top:2px;font-size:smaller;text-align:left;z-index:100;color:#ffd200;text-shadow:black 1px 1px 2px;"><strong>Invade</strong><br>&nbsp;&nbsp;&nbsp;Atk: '+(i[k].invade.att==h?'<span style="font-weight:bold;color:#00ff00;">':
"")+addCommas(i[k].invade.att)+(i[k].invade.att==h?"</span>":"")+"<br>&nbsp;&nbsp;&nbsp;Def: "+(i[k].invade.def==l?'<span style="font-weight:bold;color:#00ff00;">':"")+addCommas(i[k].invade.def)+(i[k].invade.def==l?"</span>":"")+"<br><strong>Duel</strong><br>&nbsp;&nbsp;&nbsp;Atk: "+(i[k].duel.att==j?'<span style="font-weight:bold;color:#00ff00;">':"")+addCommas(i[k].duel.att)+(i[k].duel.att==j?"</span>":"")+"<br>&nbsp;&nbsp;&nbsp;Def: "+(i[k].duel.def==g?'<span style="font-weight:bold;color:#00ff00;">':
"")+addCommas(i[k].duel.def)+(i[k].duel.def==g?"</span>":"")+"<br></div>")})}}else{var i={};$("#app"+APP+"_generalContainerBox2 > div > div.generalSmallContainer2").each(function(m,k){m=$(k).children();if(k=m.eq(0).text().trim()){i[k]={};i[k].img=m.eq(1).find("input.imgButton").attr("src").filepart();i[k].att=m.eq(2).children().eq(0).text().regex(/([0-9]+)/);i[k].def=m.eq(2).children().eq(1).text().regex(/([0-9]+)/);i[k].level=m.eq(3).text().regex(/Level ([0-9]+)/i);i[k].skills=$(m.eq(4).html().replace(/\<br\>|\s+|\n/g,
" ")).text().trim()}});if(length(i)>=length(Generals.data)){Generals.data=i;Generals.select()}else Page.to("heroes_generals","")}return true};Generals.work=function(){length(Generals.data)||Page.to("heroes_generals");return false};
Generals.to=function(a){if(!a||Player.data.general==a||a=="any")return true;if(!Generals.data[a]){GM_log('General "'+a+'" requested but not found!');return true}if(!Page.to("heroes_generals"))return false;GM_debug("Changing to General "+a);Page.click('input[src$="'+Generals.data[a].img+'"]');return false};
Generals.best=function(a){if(!Generals.data)return"any";var b="";switch(a.toLowerCase()){case "cost":b=/Decrease Soldier Cost by ([0-9]+)/i;break;case "stamina":b=/Increase Max Stamina by ([0-9]+)|\+([0-9]+) Max Stamina/i;break;case "energy":b=/Increase Max Energy by ([0-9]+)|\+([0-9]+) Max Energy/i;break;case "income":b=/Increase Income by ([0-9]+)/i;break;case "influence":b=/Bonus Influence ([0-9]+)/i;break;case "attack":b=/([+-]?[0-9]+) Player Attack/i;break;case "defense":b=/([+-]?[0-9]+) Player Defense/i;
break;case "invade":a=null;for(var c in Generals.data)if(!a||Generals.data[c].invade&&Generals.data[c].invade.att>Generals.data[a].invade.att)a=c;return a||"any";case "duel":a=null;for(c in Generals.data)if(!a||Generals.data[c].duel&&Generals.data[c].duel.att>Generals.data[a].duel.att)a=c;return a||"any";case "defend":a=null;for(c in Generals.data)if(!a||Generals.data[c].duel&&Generals.data[c].duel.def>Generals.data[a].duel.def)a=c;return a||"any";case "under level 4":if(Generals.data[Player.data.general]&&
Generals.data[Player.data.general].level<4)return Player.data.general;return Generals.random(false);default:return"any"}a=null;var d=0;for(c in Generals.data){var e=Generals.data[c].skills.regex(b);if(e)if(!a||e>d){a=c;d=e}}a&&GM_debug("Best general found: "+a);return a};Generals.random=function(a){var b=[];for(var c in Generals.data)if(a)b.push(c);else Generals.data[c].level<4&&b.push(c);return b.length?b[Math.floor(Math.random()*b.length)]:"any"};
Generals.list=function(a){var b=[];if(a)if(a.find)for(d in Generals.data)Generals.data[d].skills.indexOf(a.find)>=0&&b.push(d);else{if(a.regex){for(d in Generals.data){var c=Generals.data[d].skills.regex(a.regex);c&&b.push([d,c])}b.sort(function(e,f){return f[1]-e[1]})}}else{for(var d in Generals.data)b.push(d);b.sort()}b.unshift("any");return b};
Generals.select=function(){$("select.golem_generals").each(function(a,b){$(b).empty();var c=$(b).attr("id").slice(PREFIX.length).regex(/([^_]*)_(.*)/i);c=c?WorkerByName(c[0]).option[c[1]]:null;var d=Generals.list();for(a in d)$(b).append('<option value="'+d[a]+'"'+(d[a]==c?" selected":"")+">"+d[a]+"</value>")})};Gift=new Worker("Gift","index army_invite army_gifts");
Gift.lookup={"eq_gift_mystic_mystery.jpg":"Mystic Armor","eq_drakehelm_mystery.jpg":"Drake Helm","gift_angel_mystery2.jpg":"Battle Of Dark Legion","alchemy_serpent_mystery.jpg":"Serpentine Shield","alchemy_horn_mystery.jpg":"Poseidons Horn","gift_sea_egg_mystery.jpg":"Sea Serpent","gift_egg_mystery.jpg":"Dragon","gift_druid_mystery.jpg":"Whisper Bow","gift_armor_mystery.jpg":"Golden Hand","mystery_frost_weapon.jpg":"Frost Tear Dagger","eq_mace_mystery.jpg":"Morning Star"};
Gift.onload=function(){if(!Gift.data.uid)Gift.data.uid=[];if(!Gift.data.todo)Gift.data.todo={};if(!Gift.data.gifts)Gift.data.gifts={}};
Gift.parse=function(a){if(a)return false;if(Page.page=="index")!Gift.data.uid.length&&$("div.result").text().indexOf("has sent you a gift")>=0&&Gift.data.uid.push(1);else if(Page.page=="army_invite"){GM_debug("Gift: Checking for accepted");if(Gift.data.lastgift)if($("div.result").text().indexOf("accepted the gift")>=0){var b=Gift.data.lastgift;if(!Gift.data.todo[b].gifts)Gift.data.todo[b].gifts=[];Gift.data.todo[b].gifts.push($("div.result img").attr("src").filepart());Gift.data.lastgift=null}GM_debug("Gift: Checking for new to accept");
b=Gift.data.uid=[];if($("div.messages").text().indexOf("gift")>=0){GM_debug("Gift: Found gift div");$("div.messages img").each(function(d,e){b.push($(e).attr("uid"));GM_debug("Gift: Adding gift from "+$(e).attr("uid"))})}}else if(Page.page=="army_gifts"){var c=Gift.data.gifts={};GM_debug("Gifts found: "+$("#app"+APP+'_giftContainer div[id^="app'+APP+'_gift"]').length);$("#app"+APP+'_giftContainer div[id^="app'+APP+'_gift"]').each(function(d,e){GM_debug("Gift adding: "+$(e).text()+" = "+$("img",e).attr("src"));
d=$("img",e).attr("src").filepart();e=$(e).text().trim().replace("!","");c[d]||(c[d]={});c[d].name=e;if(Gift.lookup[e])c[d].create=Gift.lookup[e]})}return false};Gift.display=function(){var a=new Panel(this.name);a.info("Work in progress...");a.select("type","Return Gifts:",["None","Random","Same as Received"]);return a.show};
Gift.work=function(a){if(!length(Gift.data.gifts)){if(!a)return true;if(!Page.to("army_gifts"))return true}if(!a){if(Gift.data.uid.length==0)return false;return true}if(Gift.data.uid.length){if(!Page.to("army_invite"))return true;a=Gift.data.uid.shift();Gift.data.todo[a]||(Gift.data.todo[a]={});Gift.data.todo[a].time=Date.now();Gift.data.lastgift=a;GM_debug("Gift: Accepting gift from "+a);if(!Page.to("army_invite","?act=acpt&rqtp=gift&uid="+a))return true;if(Gift.data.uid.length>0)return true}Page.to("keep_alchemy");
return false};Heal=new Worker("Heal");Heal.data=null;Heal.onload=function(){if(!Heal.option.stamina)Heal.option.stamina=0;if(!Heal.option.health)Heal.option.health=0};Heal.display=function(){var a=new Panel(this.name);a.select("stamina","Heal Above",Player.data.maxstamina,{after:" stamina"});a.select("health","...And Below",Player.data.maxhealth,{after:" health"});return a.show};
Heal.work=function(a){if(Player.data.health>=Player.data.maxhealth)return false;if(Player.data.stamina<Heal.option.stamina)return false;if(Player.data.health>=Heal.option.health)return false;if(!a)return true;if(!Page.to("keep_stats"))return true;GM_debug("Heal: Healing...");$('input[value="Heal Wounds"]').length?Page.click('input[value="Heal Wounds"]'):GM_log("Danger Danger Will Robinson... Unable to heal!");return false};Idle=new Worker("Idle");Idle.data=null;
Idle.display=function(){var a=new Panel(this.name),b=["Never","Hourly","2 Hours","6 Hours","12 Hours","Daily","Weekly"];a.info("<strong>NOTE:</strong> Any workers below this will <strong>not</strong> run!<br>Use this for disabling workers you do not use.");a.general("general","Idle General","any");a.info("Check Pages:");a.select("index","Home Page",b);a.select("alchemy","Alchemy",b);a.select("quests","Quests",b);a.select("town","Town",b);a.select("battle","Battle",b);return a.show};
Idle.work=function(a){var b,c,d={index:["index"],alchemy:["keep_alchemy"],quests:["quests_quest1","quests_quest2","quests_quest3","quests_quest4","quests_quest5","quests_quest6","quests_demiquests","quests_atlantis"],town:["town_soldiers","town_blacksmith","town_magic","town_land"],battle:["battle_battle"]},e={Never:0,Hourly:36E5,"2 Hours":72E5,"6 Hours":216E5,"12 Hours":432E5,Daily:864E5,Weekly:6048E5};if(!a)return true;if(!Generals.to(Idle.option.general))return true;for(b in d)if(e[Idle.option[b]]){c=
Date.now()-e[Idle.option[b]];for(a=0;a<d[b].length;a++)if(!Page.data[d[b][a]]||Page.data[d[b][a]]<c)if(!Page.to(d[b][a]))return true}return true};Income=new Worker("Income");Income.data=null;Income.option={margin:30};Income.display=function(){var a=new Panel(this.name);a.checkbox("general","Use Best General:");a.checkbox("bank","Automatically Bank:");a.select("margin","Safety Margin",[15,30,45,60],{suffix:" seconds"});return a.show};
Income.work=function(a){if(!Income.option.margin)return false;var b=new Date;b=Player.data.cash_time-(b.getSeconds()+b.getMinutes()*60);if(b<0)b+=3600;if(b>Income.option.margin){if(a&&Income.option.bank)return Bank.work(true);return false}if(!a)return true;if(Income.option.general&&!Generals.to(Generals.best("income")))return true;GM_debug("Income: Waiting for Income...");return true};Monster=new Worker("Monster","keep_monster keep_monster_active");Monster.uid=null;
Monster.display=function(){var a=new Panel(this.name);a.info("Work in progress...");a.select("fortify","Fortify Below:",[10,20,30,40,50,60,70,80,90,100],{after:"%"});a.info("Random only...");a.select("choice","Attack:",["Random","Strongest","Weakest"]);return a.show};
Monster.parse=function(){if(Page.page=="keep_monster_active"){var a=$('img[linked="true"][size="square"]').attr("uid"),b=$('img[src$="monster_health_background.jpg"]').parent();Monster.data[a].health=Math.ceil(b.width()/b.parent().width()*100);if($('img[src$="seamonster_ship_health.jpg"]').length){b=$('img[src$="seamonster_ship_health.jpg"]').parent();Monster.data[a].defense=Math.ceil(b.width()/(b.width()+b.next().width())*100)}Monster.data[a].timer=$("#app"+APP+"_monsterTicker").text().parseTimer();
var c={};$('td.dragonContainer table table a[href^="http://apps.facebook.com/castle_age/keep.php?user="]').each(function(d,e){d=$(e).attr("href").regex(/user=([0-9]+)/i);c[d]=parseInt($(e).parent().next().text().replace(/[^0-9]/g,""))});Monster.data[a].damage=c}else if(Page.page=="keep_monster"){for(a in Monster.data)Monster.data[a].state=null;$('img[src*="dragon_list_btn_"]').each(function(d,e){d=$(e).parent().attr("href").regex(/user=([0-9]+)/i);Monster.data[d]||(Monster.data[d]={});switch($(e).attr("src").regex(/dragon_list_btn_([0-9])/)){case 2:Monster.data[d].state=
"reward";break;case 3:Monster.data[d].state="engage";break;case 4:Monster.data[d].state="complete";break;default:Monster.data[d].state="unknown";break}switch($(e).parent().parent().parent().prev().prev().html().regex(/graphics\/(.*)\./i)){case "castle_siege_list":Monster.data[d].type="legion";break;case "stone_giant_list":Monster.data[d].type="colossus";break;case "seamonster_list_red":Monster.data[d].type="serpent";break;case "deathrune_list2":Monster.data[d].type="raid";break;default:Monster.data[d].type=
"unknown";break}});for(a in Monster.data)Monster.data[a].state||delete Monster.data[a]}return false};
Monster.work=function(a){var b=[],c;if(!a)Monster.uid=null;if(!length(Monster.data))return false;if(Player.data.health<=10)return false;if(!Monster.uid||!Monster.data[Monster.uid]||Monster.data[Monster.uid]!="engage"){Monster.uid=null;for(c in Monster.data)Monster.data[c].state=="engage"&&b.push(c);if(!b.length)return false;Monster.uid=b[Math.floor(Math.random()*b.length)]}if(Queue.burn.stamina<5){if(Queue.burn.energy<10)return false;if(!Monster.data[Monster.uid].defense)return false;if(Monster.data[Monster.uid].defense>=
Monster.option.fortify)return false}if(!a)return true;if(Monster.data[Monster.uid].defense&&Monster.data[Monster.uid].defense<=Monster.option.fortify&&Queue.burn.energy>=10){if(!Generals.to(Generals.best("defend")))return true;GM_debug("Monster: Fortify "+Monster.uid);a=$('input[src$="attack_monster_button3.jpg"]:first')}else{if(!Generals.to(Generals.best("duel")))return true;GM_debug("Monster: Attack "+Monster.uid);a=$('input[src$="attack_monster_button2.jpg"]:first')}if(!a.length&&!Page.to("keep_monster",
"?user="+Monster.uid+"&mpool=3"))return true;Page.click(a);return true};Page=new Worker("Page");Page.unsortable=true;Page.page="";Page.last=null;Page.lastclick=null;Page.when=null;Page.retry=0;Page.onload=function(){if(!Page.option.timeout)Page.option.timeout=15;if(!Page.option.retry)Page.option.retry=5};Page.display=function(){var a=new Panel(this.name);a.select("timeout","Retry after ",[10,15,30,60],{after:" seconds"});a.select("retry","Reload after ",[2,3,5,10],{after:" tries"});return a.show};
Page.pageNames={index:{url:"index.php",image:null},quests_quest:{url:"quests.php",image:"tab_quest_on.gif"},quests_quest1:{url:"quests.php?land=1",image:"land_fire_sel.gif"},quests_quest2:{url:"quests.php?land=2",image:"land_earth_sel.gif"},quests_quest3:{url:"quests.php?land=3",image:"land_mist_sel.gif"},quests_quest4:{url:"quests.php?land=4",image:"land_water_sel.gif"},quests_quest5:{url:"quests.php?land=5",image:"land_demon_realm_sel.gif"},quests_quest6:{url:"quests.php?land=6",image:"land_undead_realm_sel.gif"},
quests_demiquests:{url:"symbolquests.php",image:"demi_quest_on.gif"},quests_atlantis:{url:"monster_quests.php",image:"tab_atlantis_on.gif"},battle_battle:{url:"battle.php",image:"battle_on.gif"},battle_training:{url:"battle_train.php",image:"training_grounds_on_new.gif"},battle_rank:{url:"battlerank.php",image:"tab_battle_rank_on.gif"},battle_raid:{url:"raid.php",image:"tab_raid_on.gif"},heroes_heroes:{url:"mercenary.php",image:"tab_heroes_on.gif"},heroes_generals:{url:"generals.php",image:"tab_generals_on.gif"},
town_soldiers:{url:"soldiers.php",image:"tab_soldiers_on.gif"},town_blacksmith:{url:"item.php",image:"tab_black_smith_on.gif"},town_magic:{url:"magic.php",image:"tab_magic_on.gif"},town_land:{url:"land.php",image:"tab_land_on.gif"},oracle_oracle:{url:"oracle.php",image:"oracle_on.gif"},oracle_demipower:{url:"symbols.php",image:"demi_on.gif"},oracle_treasurealpha:{url:"treasure_chest.php",image:"tab_treasure_alpha_on.gif"},oracle_treasurevanguard:{url:"treasure_chest.php?treasure_set=alpha",image:"tab_treasure_vanguard_on.gif"},
keep_stats:{url:"keep.php?user="+userID,image:"tab_stats_on.gif"},keep_eliteguard:{url:"party.php?user="+userID,image:"tab_elite_guard_on.gif"},keep_achievements:{url:"achievements.php",image:"tab_achievements_on.gif"},keep_alchemy:{url:"alchemy.php",image:"tab_alchemy_on.gif"},keep_monster:{url:"battle_monster.php",image:"tab_monster_on.jpg"},keep_monster_active:{url:"battle_monster.php",image:"dragon_view_more.gif"},army_invite:{url:"army.php",image:"invite_on.gif"},army_gifts:{url:"gift.php",image:null},
army_viewarmy:{url:"army_member.php",image:"view_army_on.gif"},army_sentinvites:{url:"army_reqs.php",image:"sent_invites_on.gif"}};
Page.identify=function(){Page.page="";$("#app"+APP+"_app_body img").each(function(a,b){a=$(b).attr("src").filepart();for(var c in Page.pageNames)if(a==Page.pageNames[c].image){Page.page=c;return}});if($("#app"+APP+"_indexNewFeaturesBox").length)Page.page="index";else if($('div[style*="giftpage_title.jpg"]').length)Page.page="army_gifts";if(Page.page!="")Page.data[Page.page]=Date.now();return Page.page};
Page.to=function(a,b){if(a==Page.page&&typeof b=="undefined")return true;b||(b="");if(a&&Page.pageNames[a]&&Page.pageNames[a].url){Page.clear();Page.last=Page.pageNames[a].url+b;Page.when=Date.now();GM_debug("Navigating to "+Page.last+" ("+Page.pageNames[a].url+")");if(unsafeWindow["a"+APP+"_get_cached_ajax"])unsafeWindow["a"+APP+"_get_cached_ajax"](Page.last,"get_body");else window.location.href="http://apps.facebook.com/castle_age/index.php?bm=1"}return false};
Page.click=function(a){if(!$(a).length){GM_debug("Page.click: Unable to find element - "+a);return false}var b=document.createEvent("MouseEvents");b.initEvent("click",true,true);$(a).get(0).wrappedJSObject.dispatchEvent(b);Page.clear();Page.lastclick=a;Page.when=Date.now();return true};Page.clear=function(){Page.last=Page.lastclick=Page.when=null;Page.retry=0};
Page.loading=function(){if(!unsafeWindow["a"+APP+"_get_cached_ajax"]){if(!Page.when||Date.now()-Page.when>=Page.option.timeout*Page.option.retry*1E3){Page.when=Date.now();window.location.href="http://apps.facebook.com/castle_age/index.php"}GM_debug("Page not loaded correctly, reloading.");return true}if($("#app"+APP+"_AjaxLoadIcon").css("display")=="none"){Page.when&&Date.now()-Page.when>Page.option.timeout*1E3&&Page.clear();return false}if(Page.when&&Date.now()-Page.when>=Page.option.timeout*1E3){GM_debug("Page.loading for 15+ seconds - retrying...");
Page.when=Date.now();if(Page.retry++>=Page.option.retry){GM_debug("Page.loading for 1+ minutes - reloading...");window.location.href="http://apps.facebook.com/castle_age/index.php"}else if(Page.last)unsafeWindow["a"+APP+"_get_cached_ajax"](Page.last,"get_body");else Page.lastclick&&Page.click(Page.lastclick)}return true};Page.reload=function(){if(!Page.when||Date.now()-Page.when>=Page.option.timeout*Page.option.retry*1E3)Page.to(Page.page||"index","")};Player=new Worker("Player","*");
Player.option=null;Player.panel=null;Player.onload=function(){var a=new Date(script_started+$("*").html().regex(/gold_increase_ticker\(([0-9]+),/)*1E3);Player.data.cash_time=a.getSeconds()+a.getMinutes()*60};
Player.parse=function(){if(!$("#app"+APP+"_app_body_container").length)return false;var a=Player.data;a.FBID=unsafeWindow.Env.user;a.cash=parseInt($("strong#app"+APP+"_gold_current_value").text().replace(/[^0-9]/g,""));a.energy=$("#app"+APP+"_energy_current_value").parent().text().regex(/([0-9]+)\s*\/\s*[0-9]+/);a.maxenergy=$("#app"+APP+"_energy_current_value").parent().text().regex(/[0-9]+\s*\/\s*([0-9]+)/);a.health=$("#app"+APP+"_health_current_value").parent().text().regex(/([0-9]+)\s*\/\s*[0-9]+/);
a.maxhealth=$("#app"+APP+"_health_current_value").parent().text().regex(/[0-9]+\s*\/\s*([0-9]+)/);a.stamina=$("#app"+APP+"_stamina_current_value").parent().text().regex(/([0-9]+)\s*\/\s*[0-9]+/);a.maxstamina=$("#app"+APP+"_stamina_current_value").parent().text().regex(/[0-9]+\s*\/\s*([0-9]+)/);a.exp=$("#app"+APP+"_st_2_5").text().regex(/([0-9]+)\s*\/\s*[0-9]+/);a.maxexp=$("#app"+APP+"_st_2_5").text().regex(/[0-9]+\s*\/\s*([0-9]+)/);a.level=$("#app"+APP+"_st_5").text().regex(/Level: ([0-9]+)!/i);a.armymax=
$("a[href*=army.php]","#app"+APP+"_main_bntp").text().regex(/([0-9]+)/);a.army=Math.min(a.armymax,501);a.upgrade=$("a[href*=keep.php]","#app"+APP+"_main_bntp").text().regex(/([0-9]+)/)||0;a.general=$("div.general_name_div3").first().text().trim();a.imagepath=$("div.general_pic_div3 img").attr("src").pathpart();if(Page.page=="keep_stats"){var b=$("div.keep_attribute_section").first();if(b.length){a.myname=$("div.keep_stat_title > span",b).text().regex(/"(.*)"/);a.rank=$("td.statsTMainback img[src*=rank_medals]").attr("src").filepart().regex(/([0-9]+)/);
b=$("div.attribute_stat_container",b);a.attack=$(b).eq(2).text().regex(/([0-9]+)/);a.defense=$(b).eq(3).text().regex(/([0-9]+)/);a.bank=parseInt($("td.statsTMainback b.money").text().replace(/[^0-9]/g,""))}}return false};
Player.work=function(){Player.data.attack||Page.to("keep_stats");Player.data.cash=parseInt($("strong#app"+APP+"_gold_current_value").text().replace(/[^0-9]/g,""));var a=new Date;a=Player.data.cash_time-(a.getSeconds()+a.getMinutes()*60);if(a<0)a+=3600;Player.data.cash_timer=a;Player.data.energy=$("#app"+APP+"_energy_current_value").parent().text().regex(/([0-9]+)\s*\/\s*[0-9]+/);Player.data.energy_timer=$("#app"+APP+"_energy_time_value").text().parseTimer();Player.data.health=$("#app"+APP+"_health_current_value").parent().text().regex(/([0-9]+)\s*\/\s*[0-9]+/);
Player.data.health_timer=$("#app"+APP+"_health_time_value").text().parseTimer();Player.data.stamina=$("#app"+APP+"_stamina_current_value").parent().text().regex(/([0-9]+)\s*\/\s*[0-9]+/);Player.data.stamina_timer=$("#app"+APP+"_stamina_time_value").text().parseTimer()};Quest=new Worker("Quest","quests_quest quests_quest1 quests_quest2 quests_quest3 quests_quest4 quests_quest5 quests_quest6 quests_demiquests quests_atlantis");Quest.land=["fire","earth","mist","water","demon","undead"];
Quest.current=null;Quest.current_id=null;Quest.what_id=null;Quest.onload=function(){if(!Quest.option.what)Quest.option.what="Influence";if(!Quest.option.general)Quest.option.general="Under Level 4"};
Quest.parse=function(a){switch(Page.page){case "quests_quest":case "quests_quest1":case "quests_quest2":case "quests_quest3":case "quests_quest4":case "quests_quest5":case "quests_quest6":var b="quest",c=$('div.title_tab_selected img[id^="app'+APP+'_land_image"]').attr("id").regex(/_image([0-9]+)$/,"");break;case "quests_demiquests":b="demiquest";break;case "quests_atlantis":b="atlantis";break;default:return false}if(!a){var d=Quest.data;$("div.quests_background,div.quests_background_sub").each(function(e,
f){if($(f).hasClass("quests_background")){if(e=$("div.qd_1 b",f).text().trim()){d[e]={};d[e].area=b;if(c)d[e].land=c;var h=$("div.quest_progress",f).text().regex(/LEVEL ([0-9]+) INFLUENCE: ([0-9]+)%/i);if(h){d[e].level=h[0];d[e].influence=h[1]}else d[e].level=d[e].influence=0;if($("div.quest_act_gen img",f).attr("title"))d[e].general=$("div.quest_act_gen img",f).attr("title");h=$("div.qd_2",f).text().replace(/[^0-9$]/g,"").regex(/^([0-9]+)\$([0-9]+)\$([0-9]+)$/);d[e].exp=h.shift();d[e].reward=(h[0]+
h[1])/2;d[e].energy=$("div.quest_req b",f).text().regex(/([0-9]+)/);if($("div.qd_1 img",f).attr("title"))d[e].item=$("div.qd_1 img",f).attr("title").trim();var l={};$("div.quest_req > div > div > div",f).each(function(j,g){j=$("img",g).attr("title");l[j]=$(g).text().regex(/([0-9]+)/)});if(l.length)d[e].units=l}}else if(e=$("div.quest_sub_title",f).text().trim()){d[e]={};d[e].area=b;if(c)d[e].land=c;if(h=$("div.quest_sub_progress",f).text().regex(/LEVEL ([0-9]+) INFLUENCE: ([0-9]+)%/i)){d[e].level=
h[0];d[e].influence=h[1]}else d[e].level=d[e].influence=0;h=$("div.qd_2_sub",f).text().replace(/[^0-9$]/g,"").regex(/^([0-9]+)\$([0-9]+)\$([0-9]+)$/);d[e].exp=h.shift();d[e].reward=(h[0]+h[1])/2;d[e].energy=$("div.qd_3_sub",f).text().regex(/([0-9]+)/)}});Quest.select()}};
Quest.display=function(){var a,b=[];for(a in Quest.data)Quest.data[a].item&&b.push(Quest.data[a].item);a=new Panel(this.name);a.select("general","General:",["any","Under Level 4","Influence"]);Quest.what_id=a.select("what","Quest for:",Array.concat(["Nothing","Influence","Experience","Cash"],unique(b.sort())));Quest.current_id=a.info("None","current","Current:");return a.show};
Quest.work=function(a){if(Quest.option.firstrun||!length(Quest.data)){var b=Quest.pages.split(" ");if(!a){Quest.option.firstrun=1;Settings.Save("option",Quest);return true}var c=Quest.option.firstrun++;if(b[c]){Settings.Save("option",Quest);Page.to(b[c]);return true}delete Quest.option.firstrun;Settings.Save("option",Quest);Quest.select();return false}b=null;if(Quest.option.what=="Nothing")return false;for(c in Quest.data){switch(Quest.option.what){case "Influence":if(Quest.data[c].influence>=100)continue;
if(b&&Quest.data[c].energy>=Quest.data[b].energy)continue;break;case "Experience":if(b&&Quest.data[c].energy/Quest.data[c].exp>=Quest.data[b].energy/Quest.data[b].exp)continue;break;case "Cash":if(b&&Quest.data[c].energy/Quest.data[c].reward>=Quest.data[b].energy/Quest.data[b].reward)continue;break;default:if(!Quest.data[c].item||Quest.data[c].item!=Quest.option.what)continue;if(b&&Quest.data[c].energy>Quest.data[b].energy)continue;break}b=c}if(b!=Quest.current)if(Quest.current=b){GM_debug("Quest: Wanting to perform - "+
b+" (energy: "+Quest.data[b].energy+")");$("#"+Quest.current_id).html("<strong>Current:</strong> "+b+" (energy: "+Quest.data[b].energy+")")}if(!b)return false;if(Quest.data[b].energy>Queue.burn.energy)return false;if(!a)return true;if(Quest.data[b].general){if(!Generals.to(Quest.data[b].general))return true}else if(!Generals.to(Generals.best(Quest.option.general)))return true;switch(Quest.data[b].area){case "quest":if(!Page.to("quests_quest"+Quest.data[b].land))return true;break;case "demiquest":if(!Page.to("quests_demiquests"))return true;
break;case "atlantis":if(!Page.to("quests_atlantis"))return true;break;default:GM_debug("Quest: Can't get to quest area!");return false}GM_debug("Quest: Performing - "+b+" (energy: "+Quest.data[b].energy+")");Page.click('div.action[title^="'+b+'"] input[type="image"]')||Page.reload();return true};
Quest.select=function(){var a=[];for(var b in Quest.data)Quest.data[b].item&&a.push(Quest.data[b].item);a=["Nothing","Influence","Experience","Cash"].concat(unique(a.sort()));$("#"+Quest.what_id).empty();for(b in a)$("#"+Quest.what_id).append('<option value="'+a[b]+'"'+(a[b]==Quest.option.what?" selected":"")+">"+a[b]+"</value>")};Queue=new Worker("Queue","*");Queue.data={};
Queue.option={delay:5,clickdelay:5,queue:["Page","Queue","Income","Quest","Monster","Battle","Heal","Bank","Alchemy","Town","Blessing","Gift","Upgrade","Idle","Raid"]};Queue.runfirst=[];Queue.unsortable=true;Queue.lastclick=Date.now();Queue.lastrun=Date.now();Queue.burn={stamina:false,energy:false};
Queue.onload=function(){if(!Queue.option.queue)Queue.option.queue=[];if(!Queue.data.current)Queue.data.current=null;if(!Queue.option.stamina)Queue.option.stamina=0;if(!Queue.option.energy)Queue.option.energy=0;var a={};for(var b in Queue.option.queue){var c=WorkerByName(Queue.option.queue[b]);if(c)a[c.name]=true}for(b in Workers)if(!(a[Workers[b].name]||!Workers[b].work||!Workers[b].display)){GM_log("Adding "+Workers[b].name+" to Queue");Workers[b].unsortable?Queue.option.queue.unshift(Workers[b].name):
Queue.option.queue.push(Workers[b].name)}for(b in Queue.option.queue)if((c=WorkerByName(Queue.option.queue[b]))&&c.priv_id){if(Queue.data.current&&c.name==Queue.data.current){GM_debug("Queue: Trigger "+c.name+" (continue after load)");$("#"+c.priv_id+" > h3 > a").css("font-weight","bold")}$("#golem_config").append($("#"+c.priv_id))}$(document).click(function(){Queue.lastclick=Date.now()})};
Queue.display=function(){$btn=$('<button id="golem_pause">pause</button>').button({text:false,icons:{primary:Queue.option.pause?"ui-icon-play":"ui-icon-pause"}}).click(function(){Queue.option.pause^=true;GM_debug("State: "+(Queue.option.pause?"paused":"running"));$(this).button("option",{icons:{primary:Queue.option.pause?"ui-icon-play":"ui-icon-pause"}});Page.clear();Config.updateOptions()});$("#golem_buttons").prepend($btn);var a=new Panel(this.name);a.info("Drag the other panels into the order you wish them run.");
a.text("delay","Delay Between Events",{after:"secs",size:3});a.text("clickdelay","Delay After Mouse Click",{after:"secs",size:3});a.select("stamina","Keep Stamina:",Player.data.maxstamina);a.select("energy","Keep Energy:",Player.data.maxenergy);return a.show};
Queue.run=function(){var a,b,c=false,d=Date.now();if(!(Queue.option.pause||d-Queue.lastclick<Queue.option.clickdelay*1E3||d-Queue.lastrun<Queue.option.delay*1E3)){Queue.lastrun=d;if(!Page.loading()){Queue.burn.stamina=Math.max(0,Player.data.stamina-Queue.option.stamina);Queue.burn.energy=Math.max(0,Player.data.energy-Queue.option.energy);for(a in Workers)Workers[a].work&&!Workers[a].display&&Workers[a].work(false);for(a in Queue.option.queue){b=WorkerByName(Queue.option.queue[a]);if(!(!b||!b.work||
!b.display))if(b.work(Queue.data.current==b.name)){Settings.Save(b);if(!c){c=true;if(Queue.data.current!=b.name){b.priv_since=d;if(Queue.data.current){GM_debug("Queue: Interrupt "+Queue.data.current);$("#"+WorkerByName(Queue.data.current).priv_id+" > h3 > a").css("font-weight","normal")}Queue.data.current=b.name;$("#"+b.priv_id+" > h3 > a").css("font-weight","bold");GM_debug("Queue: Trigger "+b.name)}}}else{Settings.Save(b);if(Queue.data.current==b.name){Queue.data.current=null;$("#"+b.priv_id+" > h3 > a").css("font-weight",
"normal");GM_debug("Queue: End "+b.name)}}}Settings.Save(Queue)}}};Raid=new Worker("Raid","battle_raid",{stamina:true});Raid.onload=function(){if(!Raid.option.type)Raid.option.type="Invade"};Raid.display=function(){var a=new Panel(this.name);a.info("In progress...");a.select("type","Attack Type:",["Invade","Duel"]);a.general("general","General:");return a.show};
Raid.parse=function(){if($('input[name="help with raid"]').length){var a=$('img[linked="true"][size="square"]').attr("uid"),b=$('img[src$="monster_health_background.jpg"]').parent();Raid.data[a].health=Math.ceil(b.width()/b.parent().width()*100);Raid.data[a].timer=$("#app"+APP+"_monsterTicker").text().parseTimer();var c={};$('td.dragonContainer table table a[href^="http://apps.facebook.com/castle_age/keep.php?user="]').each(function(e,f){e=$(f).attr("href").regex(/user=([0-9]+)/i);c[e]=parseInt($(f).parent().next().text().replace(/[^0-9]/g,
""))});Raid.data[a].damage=c}else{var d={};$('img[src$="dragon_list_btn_3.jpg"]').each(function(e,f){e=$(f).parent().attr("href").regex(/user=([0-9]+)/i);d[e]={}});for(a in d)Raid.data[a]||(Raid.data[a]={});for(a in Raid.data)d[a]||delete Raid.data[a]}return false};
Raid.work=function(a){if(!length(Raid.data))return false;if(Player.data.health<=10)return false;var b=null;for(var c in Raid.data)b=c;if(!b)return false;if(!a)return true;if(!Generals.to(Raid.option.general))return true;a=Raid.option.type=="Invade"?$('input[src$="raid_attack_button.gif"]:first'):$('input[src$="raid_attack_button2.gif"]:first');if(!a.length&&!Page.to("battle_raid","?user="+b))return true;a=Raid.option.type=="Invade"?$('input[src$="raid_attack_button.gif"]:first'):$('input[src$="raid_attack_button2.gif"]:first');
Page.click(a);return true};Town=new Worker("Town","town_soldiers town_blacksmith town_magic town_land");Town.units={};Town.cache={};Town.table=null;Town.header={};
Town.blacksmith={Weapon:/avenger|axe|blade|bow|dagger|halberd|mace|morningstar|rod|spear|staff|stave|sword|talon|trident|wand|Dragonbane|Ironhart's Might|Judgement|Oathkeeper/i,Shield:/buckler|shield|dreadnought|Defender|Sword of Redemption/i,Helmet:/cowl|crown|helm|horns|mask|veil/i,Gloves:/gauntlet|glove|hand/i,Armor:/armor|chainmail|cloak|pauldrons|plate|robe/i,Amulet:/amulet|bauble|charm|jewel|memento|orb|shard|trinket|Paladin's Oath|Poseidons Horn/i};
Town.onload=function(){if(!Town.data.soldiers)Town.data.soldiers={};if(!Town.data.blacksmith)Town.data.blacksmith={};if(!Town.data.magic)Town.data.magic={};if(!Town.data.land)Town.data.land={}};
Town.parse=function(a){if(a){if(Page.page=="town_blacksmith"){c=Town.data.blacksmith;$("tr.eq_buy_row,tr.eq_buy_row2").each(function(d,e){d=$("div.eq_buy_txt strong:first-child",e).text().trim();c[d].type&&$("div.eq_buy_txt strong:first-child",e).parent().append("<br>"+c[d].type)})}if(Page.page!="town_land"){a=$('<tr><td><div style="padding:9px 0px 0px 15px; width:725px; height:28px;">Sort by <a id="sort_none">Normal</a> / <a id="sort_attack">Attack</a> / <a id="sort_defense">Defense</a></div></td></tr>');
$("div",a).css({backgroundImage:$('div[style*="hero_divider.gif"]').first().css("background-image"),color:"#fff",fontSize:"16px",fontWeight:"bold"});$("#sort_none",a).click(function(){Town.sortBy()});$("#sort_attack",a).click(function(){Town.sortBy("att")});$("#sort_defense",a).click(function(){Town.sortBy("def")});$(this.table).prepend(a)}}else{if(Page.page=="town_land"){var b=Town.data.land={};$("tr.land_buy_row,tr.land_buy_row_unique").each(function(d,e){d=$("img",e).attr("alt");b[d]={};b[d].income=
$(".land_buy_info .gold",e).text().replace(/[^0-9]/g,"").regex(/([0-9]+)/);b[d].max=$(".land_buy_info",e).text().regex(/Max Allowed For your level: ([0-9]+)/i);b[d].cost=$(".land_buy_costs .gold",e).text().replace(/[^0-9]/g,"").regex(/([0-9]+)/);b[d].own=$(".land_buy_costs span",e).text().replace(/[^0-9]/g,"").regex(/([0-9]+)/)});GM_debug("Land: "+Town.data.land.toSource())}else{if(Page.page=="town_soldiers")var c=Town.data.soldiers={};else if(Page.page=="town_blacksmith")c=Town.data.blacksmith={};
else if(Page.page=="town_magic")c=Town.data.magic={};a=$("tr.eq_buy_row,tr.eq_buy_row2");a.each(function(d,e){var f=$("div.eq_buy_txt strong:first-child",e).text().trim();Town.cache[f]=e;c[f]={};var h=$("div.eq_buy_costs strong:first-child",e).text().replace(/[^0-9]/g,"");if(h){c[f].cost=parseInt(h);c[f].buy=[];$('div.eq_buy_costs select[name="amount"]:first option',e).each(function(l,j){c[f].buy.push(parseInt($(j).val()))})}c[f].own=$("div.eq_buy_costs span:first-child",e).text().regex(/([0-9]+)/);
c[f].att=$("div.eq_buy_stats div:first-child",e).text().regex(/([0-9]+)/);c[f].def=$("div.eq_buy_stats div:last-child",e).text().regex(/([0-9]+)/);if(Page.page=="town_blacksmith")for(d in Town.blacksmith)if(f.match(Town.blacksmith[d]))c[f].type=d});Town.table=$(a).first().parent();this.header={};$(this.table).children().each(function(d,e){$(e).attr("class")||(Town.header[d]=[e,$(e).next()])});Town.units=c}Page.page!="town_land"&&length(Town.data.soldiers)&&length(Town.data.blacksmith)&&length(Town.data.magic)&&
Town.getValues()}return true};Town.display=function(){var a=new Panel(this.name);a.info("In progress...");a.checkbox("general","Use Best General:");a.select("number","Buy Number:",["None","Maximum","Match Army"]);a.select("units","Buy Type:",["All","Best Offense","Best Defense","Best of Both"]);return a.show};
Town.work=function(a){if(!length(Town.data.soldiers)){if(!a)return true;if(!Page.to("town_soldiers"))return true}if(!length(Town.data.blacksmith)){if(!a)return true;if(!Page.to("town_blacksmith"))return true}if(!length(Town.data.magic)){if(!a)return true;if(!Page.to("town_magic"))return true}if(!Town.option.number)return false;var b=Math.min(Town.option.number=="Maximum"?501:Player.data.army,501),c=null,d=0,e=Town.data.soldiers;for(var f in e){d=0;if(e[f].cost)if(!(e[f].own>=b))if(!(c&&Town.option.units==
"Best Offense"&&e[f].att<=c.att))if(!(c&&Town.option.units=="Best Defense"&&e[f].def<=c.def))if(!(c&&Town.option.units=="Best of Both"&&(e[f].att<=c.att||e[f].def<=c.def))){for(var h in e[f].buy)if(b-e[f].own>=e[f].buy[h])d=e[f].buy[h];GM_debug("Thinking about buying: "+d+" of "+f+" at $"+d*e[f].cost);if(d){c=f;break}}}if(!c)return false;if(!a){GM_debug("Want to buy "+d+" x "+c+" at $"+d*e[c].cost);return true}return false};
Town.sortBy=function(a){if(a){var b=[],c=a=="att"?"def":"att";for(d in Town.units)b.push(d);b.sort(function(e,f){return Town.units[f][a]+0.7*Town.units[f][c]-(Town.units[e][a]+0.7*Town.units[e][c])});for(d in b)$(Town.table).append($(Town.cache[b[d]]));for(d in Town.header)$(Town.header[d]).css("display","none")}else{for(var d in Town.units)$(Town.table).append($(Town.cache[d]));for(d in Town.header){$($(Town.header[d][1])).before($(Town.header[d][0]));$(Town.header[d][0]).css("display","table-row")}}};
Town.getValues=function(){Town.data.invade={attack:getAttDef(Town.data.soldiers,function(a,b){a.push(b)},"att",Player.data.army,"invade")+getAttDef(Town.data.blacksmith,function(a,b,c){c[b].type=="Weapon"&&a.push(b)},"att",Player.data.army,"invade")+getAttDef(Town.data.blacksmith,function(a,b,c){c[b].type!="Weapon"&&a.push(b)},"att",Player.data.army,"invade")+getAttDef(Town.data.magic,function(a,b){a.push(b)},"att",Player.data.army,"invade"),defend:getAttDef(Town.data.soldiers,function(a,b){a.push(b)},
"def",Player.data.army,"invade")+getAttDef(Town.data.blacksmith,function(a,b,c){c[b].type=="Weapon"&&a.push(b)},"def",Player.data.army,"invade")+getAttDef(Town.data.blacksmith,function(a,b,c){c[b].type!="Weapon"&&a.push(b)},"def",Player.data.army,"invade")+getAttDef(Town.data.magic,function(a,b){a.push(b)},"def",Player.data.army,"invade")};Town.data.duel={attack:getAttDef(Town.data.blacksmith,function(a,b,c){c[b].type=="Weapon"&&a.push(b)},"att",1,"duel")+getAttDef(Town.data.blacksmith,function(a,
b,c){c[b].type=="Shield"&&a.push(b)},"att",1,"duel")+getAttDef(Town.data.blacksmith,function(a,b,c){c[b].type=="Helmet"&&a.push(b)},"att",1,"duel")+getAttDef(Town.data.blacksmith,function(a,b,c){c[b].type=="Gloves"&&a.push(b)},"att",1,"duel")+getAttDef(Town.data.blacksmith,function(a,b,c){c[b].type=="Armor"&&a.push(b)},"att",1,"duel")+getAttDef(Town.data.blacksmith,function(a,b,c){c[b].type=="Amulet"&&a.push(b)},"att",1,"duel")+getAttDef(Town.data.magic,function(a,b){a.push(b)},"att",1,"duel"),defend:getAttDef(Town.data.blacksmith,
function(a,b,c){c[b].type=="Weapon"&&a.push(b)},"def",1,"duel")+getAttDef(Town.data.blacksmith,function(a,b,c){c[b].type=="Shield"&&a.push(b)},"def",1,"duel")+getAttDef(Town.data.blacksmith,function(a,b,c){c[b].type=="Helmet"&&a.push(b)},"def",1,"duel")+getAttDef(Town.data.blacksmith,function(a,b,c){c[b].type=="Gloves"&&a.push(b)},"def",1,"duel")+getAttDef(Town.data.blacksmith,function(a,b,c){c[b].type=="Armor"&&a.push(b)},"def",1,"duel")+getAttDef(Town.data.blacksmith,function(a,b,c){c[b].type==
"Amulet"&&a.push(b)},"def",1,"duel")+getAttDef(Town.data.magic,function(a,b){a.push(b)},"def",1,"duel")}};Update=new Worker("Update");Update.data=null;Update.option=null;Update.found=false;Update.onload=function(){var a=$('<button name="Script Update" id="golem_update">Check</button>').button().click(function(){Update.now(true)});$("#golem_buttons").append(a)};
Update.now=function(a){if(Update.found)window.location.href="http://userscripts.org/scripts/source/67412.user.js";else{var b=Settings.GetValue("lastUpdateCheck",0);if(a||Date.now()-b>864E5){Settings.SetValue("lastUpdateCheck",Date.now().toString());GM_xmlhttpRequest({method:"GET",url:"http://userscripts.org/scripts/show/67412",onload:function(c){if(c.readyState==4&&c.status==200){c=$(c.responseText);a&&$("#golem_request").remove();c=$("#summary",c).text().regex(/Version:[^0-9.]+([0-9.]+)/i);if(c>
VERSION){Update.found=true;$("#golem_update span").text("Install");if(a){$("#golem_config").after('<div id="golem_request" title="Castle Age Golem"><p>There is a new version of Castle Age Golem available.</p><p>Current&nbsp;version:&nbsp;'+VERSION+", New&nbsp;version:&nbsp;"+c+"</p></div>");$("#golem_request").dialog({modal:true,buttons:{Install:function(){$(this).dialog("close");window.location.href="http://userscripts.org/scripts/source/67412.user.js"},Skip:function(){$(this).dialog("close")}}})}GM_log("New version available: "+
c)}else if(a){$("#golem_config").after('<div id="golem_request" title="Castle Age Golem"><p>There are no new versions available.</p></div>');$("#golem_request").dialog({modal:true,buttons:{Ok:function(){$(this).dialog("close")}}})}}}})}}};Upgrade=new Worker("Upgrade","keep_stats");Upgrade.onload=function(){if(!Upgrade.data.run)Upgrade.data.run=0};
Upgrade.parse=function(){var a=$("div.results");if(Upgrade.data.working&&a.length&&a.text().match(/You just upgraded your/i)){Upgrade.data.working=false;Upgrade.data.run++;if(Upgrade.data.run>=Upgrade.option.order.length)Upgrade.data.run=0}return false};
Upgrade.display=function(){var a=new Panel(this.name);a.info("Points will be allocated in this order, add multiple entries if wanted (ie, 3x Attack and 1x Defense would put &frac34; on Attack and &frac14; on Defense)");a.multiple("order","Stats:",["Energy","Stamina","Attack","Defense","Health"]);return a.show};
Upgrade.work=function(a){if(!Upgrade.option.order||!Upgrade.option.order.length||!Player.data.upgrade)return false;if(!a)return true;if(!Page.to("keep_stats"))return true;Upgrade.data.working=true;if(Upgrade.data.run>=Upgrade.option.order.length)Upgrade.data.run=0;switch(Upgrade.option.order[Upgrade.data.run]){case "Energy":if(Page.click('a[href$="?upgrade=energy_max"]'))return true;break;case "Stamina":if(Page.click('a[href$="?upgrade=stamina_max"]'))return true;break;case "Attack":if(Page.click('a[href$="?upgrade=attack"]'))return true;
break;case "Defense":if(Page.click('a[href$="?upgrade=defense"]'))return true;break;case "Health":if(Page.click('a[href$="?upgrade=health_max"]'))return true;break}if(!Page.to("index"))return true;return false};
