/*jslint
*/

Quest.rts = 1318744182;		// Sun Oct 16 05:49:42 2011 UTC

Quest.rdata =				// #538
{
	'a demonic transformation':			{ 'reps_q4':  40 },
	'a forest in peril':				{ 'reps_d4':   9 },
	'a kidnapped princess':				{ 'reps_d1':  10 },
	'a new dawn':						{ 'reps_q12':  7 },
	'a surprise from terra':			{ 'reps_q12': 12 },
	'accessing the chamber':			{ 'reps_q16':  0 },
	'across the sea':					{ 'reps_q11':  8 },
	'aid corvintheus':					{ 'reps_d3':   9 },
	'aid the angels':					{ 'reps_q9':  17 },
	'approach the prayer chamber':		{ 'reps_d1':  12 },
	'approach the tree of life':		{ 'reps_d4':  12 },
	'ascent to the skies':				{ 'reps_q8':  14 },
	'attack from above':				{ 'reps_q9':  17 },
	'attack undead guardians':			{ 'reps_q6':  24 },
	'aurelius':							{ 'reps_q11': 11 },
	'aurelius outpost':					{ 'reps_q11':  9 },
	'avatar of vengeance':				{ 'reps_q16':  0 },
	'avoid an avalanche':				{ 'reps_q14':  0 },
	'avoid detection':					{ 'reps_q12':  0 },
	'avoid ensnarements':				{ 'reps_q3':  34 },
	'avoid fungal poison':				{ 'reps_q12':  0 },
	'avoid patrols':					{ 'reps_q14':  0 },
	'avoid poison':						{ 'reps_q12':  0 },
	'avoid shades':						{ 'reps_q12':  0 },
	'avoid the guards':					{ 'reps_q8':  14 },
	'avoid the patrols':				{ 'reps_q9':  17 },
	'banish the horde':					{ 'reps_q9':  17 },
	'banish undead':					{ 'reps_q15':  0 },
	'battle a wraith':					{ 'reps_q2':  16 },
	'battle earth and fire demons':		{ 'reps_q4':  16 },
	'battle gang of bandits':			{ 'reps_q1':   8 },
	'battle orc captain':				{ 'reps_q3':  15 },
	'battle the black dragon':			{ 'reps_q4':  14 },
	'battle the ent':					{ 'reps_d4':  12 },
	'battling the demons':				{ 'reps_q9':  17 },
	'being followed':					{ 'reps_q7':  15 },
	'blood wing king of the dragons':	{ 'reps_d2':  20 },
	'brace yourself':					{ 'reps_q14':  0 },
	'breach prison':					{ 'reps_q12':  0 },
	'breach the barrier':				{ 'reps_q8':  14 },
	'breach the keep entrance':			{ 'reps_d3':  12 },
	'breaching the gates':				{ 'reps_q7':  15 },
	'break aurelius guard':				{ 'reps_q11':  0 },
	'break evil seal':					{ 'reps_q7':  17 },
	'break front line':					{ 'reps_q15':  0 },
	'break magic barrier':				{ 'reps_q16':  0 },
	'break the lichs spell':			{ 'reps_d3':  12 },
	'break the line':					{ 'reps_q10':  0 },
	'break through':					{ 'reps_q15':  0 },
	'breaking through the guard':		{ 'reps_q9':  15 },
	'bridge of elim':					{ 'reps_q8':  11 },
	'bridge of fire':					{ 'reps_q14': 11 },
	'burn barracks':					{ 'reps_q14':  0 },
	'burning gates':					{ 'reps_q7':  10 },
	'burning of karth':					{ 'reps_q14': 15 },
	'bury corpses':						{ 'reps_q15':  0 },
	'call of arms':						{ 'reps_q6':  25 },
	'calm before the storm':			{ 'reps_q13': 10 },
	'calm your soul':					{ 'reps_q15':  0 },
	'capture army':						{ 'reps_q14':  0 },
	'cast aura of night':				{ 'reps_q5':  32 },
	'cast barrier':						{ 'reps_q14':  0 },
	'cast blizzard':					{ 'reps_q10': 15 },
	'cast fire aura':					{ 'reps_q6':  24 },
	'cast holy light':					{ 'reps_q6':  24 },
	'cast holy light spell':			{ 'reps_q5':  24 },
	'cast holy shield':					{ 'reps_d3':  12 },
	'cast illuminating light':			{ 'reps_q16':  0 },
	'cast meteor':						{ 'reps_q5':  32 },
	'cast poison shield':				{ 'reps_q13':  0 },
	'cast regrowth':					{ 'reps_q13':  0 },
	'castle of the black lion':			{ 'reps_d5':  13 },
	'castle of the damn':				{ 'reps_d3':  21 },
	'caverns of eternity':				{ 'reps_q16':  9 },
	'channel excalibur':				{ 'reps_q8':  14 },
	'channel runestones':				{ 'reps_q12':  0 },
	'charge ahead':						{ 'reps_q10':  0 },
	'charge the castle':				{ 'reps_q7':  15 },
	'chasm of fire':					{ 'reps_q10': 10 },
	'city of clouds':					{ 'reps_q8':  11 },
	'cleanse your soul':				{ 'reps_q16':  0 },
	'clear haze':						{ 'reps_q13':  0 },
	'clear the rocks':					{ 'reps_q11':  0 },
	'cliffs of despair':				{ 'reps_q16':  0 },
	'climb castle cliffs':				{ 'reps_q11':  0 },
	'climb the mountain':				{ 'reps_q8':  14 },
	'climb walls':						{ 'reps_q14':  0 },
	'close the black portal':			{ 'reps_d1':  12 },
	'collect artifact shards':			{ 'reps_q13':  0 },
	'collect astral souls':				{ 'reps_q12':  0 },
	'collect runestones':				{ 'reps_q12':  0 },
	'confront celesta':					{ 'reps_q14':  0 },
	'confront figure':					{ 'reps_q14':  0 },
	'confront the black lion':			{ 'reps_d5':  12 },
	'confront the rebels':				{ 'reps_q10': 10 },
	'consult aurora':					{ 'reps_d4':  12 },
	'corruption of nature':				{ 'reps_d4':  20 },
	'counter life drain':				{ 'reps_q14':  0 },
	'cover tracks':						{ 'reps_q7':  19 },
	'create artifact relic':			{ 'reps_q13':  0 },
	'create wall':						{ 'reps_q12':  0 },
	'cross astral bridge':				{ 'reps_q16':  0 },
	'cross chasm':						{ 'reps_q15':  0 },
	'cross lava pools':					{ 'reps_q14':  0 },
	'cross lava river':					{ 'reps_q7':  20 },
	'cross the bridge':					{ 'reps_q8':  14, 'reps_q10':  0 },
	'cross the chasm':					{ 'reps_q16':  0 },
	'cross the falls':					{ 'reps_q13':  0 },
	'cross the moat':					{ 'reps_q11':  0 },
	'crossing the chasm':				{ 'reps_q2':  13, 'reps_q8':  14 },
	'crossing the white plains':		{ 'reps_q14': 10 },
	'cure infested soldiers':			{ 'reps_q6':  25 },
	'dark chasm':						{ 'reps_q15':  0 },
	'dark heart of the woods':			{ 'reps_q12':  9 },
	'deal final blow to bloodwing':		{ 'reps_d2':  12 },
	'death of a forest':				{ 'reps_q13':  8 },
	'deathrune castle':					{ 'reps_q7':  12 },
	'decipher magic':					{ 'reps_q15':  0 },
	'decipher the clues':				{ 'reps_q9':  17 },
	'defeat and heal feral animals':	{ 'reps_d4':  12 },
	'defeat angelic sentinels':			{ 'reps_q8':  14 },
	'defeat astral wolves':				{ 'reps_q12':  0 },
	'defeat bear form':					{ 'reps_q11':  0 },
	'defeat bloodwing':					{ 'reps_d2':  12 },
	'defeat chimerus':					{ 'reps_d1':  12 },
	'defeat darien woesteel':			{ 'reps_d5':   9 },
	'defeat demonic guards':			{ 'reps_q7':  17 },
	'defeat fire elementals':			{ 'reps_q10':  0 },
	'defeat frost minions':				{ 'reps_q3':  40 },
	'defeat ghoul':						{ 'reps_q15':  0 },
	'defeat guardian':					{ 'reps_q12':  0 },
	'defeat guards':					{ 'reps_q12':  0, 'reps_q15':  0 },
	'defeat keeper':					{ 'reps_q15':  0 },
	'defeat lion defenders':			{ 'reps_q11':  0 },
	'defeat lothar':					{ 'reps_q12':  0 },
	'defeat orc patrol':				{ 'reps_q8':  14 },
	'defeat paladin':					{ 'reps_q14':  0 },
	'defeat phalanx':					{ 'reps_q15':  0 },
	'defeat rebels':					{ 'reps_q10':  0 },
	'defeat rock elementals':			{ 'reps_q13':  0 },
	'defeat shadow rays':				{ 'reps_q16':  0 },
	'defeat shadowstalkers':			{ 'reps_q16':  0 },
	'defeat snow giants':				{ 'reps_q3':  24 },
	'defeat spirits':					{ 'reps_q12':  0 },
	'defeat sylvana':					{ 'reps_q14':  0 },
	'defeat the bandit leader':			{ 'reps_q1':   5 },
	'defeat the banshees':				{ 'reps_q5':  25 },
	'defeat the black lion army':		{ 'reps_d5':  12 },
	'defeat the demonic guards':		{ 'reps_d1':  12 },
	'defeat the demons':				{ 'reps_q9':  17 },
	'defeat the kobolds':				{ 'reps_q10':  0 },
	'defeat the patrols':				{ 'reps_q9':  17 },
	'defeat the seraphims':				{ 'reps_q8':  14 },
	'defeat tiger form':				{ 'reps_q11':  0 },
	'defeat treants':					{ 'reps_q12':  0 },
	'defeat wights':					{ 'reps_q15':  0 },
	'defeat wolverines':				{ 'reps_q13':  0 },
	'defend the village':				{ 'reps_d3':  12 },
	'desert temple':					{ 'reps_q11': 12 },
	'destroy black oozes':				{ 'reps_q11':  0 },
	'destroy elementals':				{ 'reps_q16':  0 },
	'destroy fire dragon':				{ 'reps_q4':  10 },
	'destroy fire elemental':			{ 'reps_q4':  16 },
	'destroy fire elementals':			{ 'reps_q14':  0 },
	'destroy horde of ghouls & trolls':	{ 'reps_q4':   9 },
	'destroy mushrooms':				{ 'reps_q13':  0 },
	'destroy path':						{ 'reps_q14':  0 },
	'destroy scourge':					{ 'reps_q13':  0 },
	'destroy spores':					{ 'reps_q12':  0 },
	'destroy the black gate':			{ 'reps_d1':  12 },
	'destroy the black portal':			{ 'reps_d1':  12 },
	'destroy the bolted door':			{ 'reps_d3':  12 },
	'destroy undead crypt':				{ 'reps_q1':   4 },
	'destroy ward':						{ 'reps_q15':  0 },
	'destruction abound':				{ 'reps_q8':  11 },
	'determine cause of corruption':	{ 'reps_d5':  12 },
	'diciphering the message':			{ 'reps_q16':  0 },
	'dig up star metal':				{ 'reps_d3':  12 },
	'disarm townspeople':				{ 'reps_q11':  0 },
	'discover cause of corruption':		{ 'reps_d4':  12 },
	'dismantle orc patrol':				{ 'reps_q3':  32 },
	'dispatch corrupted soldiers':		{ 'reps_q13':  0 },
	'dispatch lothar':					{ 'reps_q12':  0 },
	'dispatch more cultist guards':		{ 'reps_d1':  12 },
	'dispatch patrol':					{ 'reps_q14':  0 },
	'dispel enchantment':				{ 'reps_q16':  0 },
	'distract the demons':				{ 'reps_q9':  17 },
	'don armor':						{ 'reps_q14':  0 },
	'dragon slayer':					{ 'reps_d2':  14 },
	'druidic prophecy':					{ 'reps_q11':  9 },
	"duel cefka's knight champion":		{ 'reps_q4':  10 },
	'duel with guards':					{ 'reps_q12':  0 },
	'dwarven stronghold':				{ 'reps_q10': 10 },
	'eastern corridor':					{ 'reps_q11':  0 },
	'eerie silence':					{ 'reps_q15':  0 },
	'elekin the dragon slayer':			{ 'reps_d2':  10 },
	'enchant weapon':					{ 'reps_q14':  0 },
	'end of the road':					{ 'reps_q9':  17 },
	'energy rift':						{ 'reps_q14': 11 },
	'enlist captain morgan':			{ 'reps_q11':  0 },
	'entrance':							{ 'reps_a2':   0 },
	'entrance denied':					{ 'reps_q12': 12 },
	'entrance of time':					{ 'reps_q16':  0 },
	'entrance to terra':				{ 'reps_q1':   7 },
	'entrap souls':						{ 'reps_q15':  0 },
	'equip soldiers':					{ 'reps_q6':  25 },
	'eradicate spores':					{ 'reps_q13':  0 },
	'escape from trakan':				{ 'reps_q12':  7 },
	'escape the darkness':				{ 'reps_q16':  0 },
	'escape trakan':					{ 'reps_q12':  0 },
	'escape woods':						{ 'reps_q12':  0 },
	'escaping the chaos':				{ 'reps_q9':  17 },
	'escaping the stronghold':			{ 'reps_q9':  10 },
	'exiting the chamber':				{ 'reps_q16':  0 },
	'explore dead forests':				{ 'reps_q12':  0 },
	'explore merchant plaza':			{ 'reps_q11': 17 },
	'explore mist expanse':				{ 'reps_q12':  0 },
	'explore mist ruins':				{ 'reps_q12':  0 },
	'explore rodinia':					{ 'reps_q15':  0 },
	'explore the temple':				{ 'reps_q11':  0 },
	'extinguish desert basilisks':		{ 'reps_q11':  0 },
	'extinguish the fires':				{ 'reps_q8':  14 },
	'falls of jiraya':					{ 'reps_q1':   8 },
	'family ties':						{ 'reps_d5':  11 },
	'felthias fields':					{ 'reps_q12': 14 },
	'fend off demons':					{ 'reps_q7':  20 },
	'fiery awakening':					{ 'reps_q7':  12 },
	"fight cefka's shadow guard":		{ 'reps_q4':  10 },
	'fight demonic worshippers':		{ 'reps_q5':  24 },
	'fight dragon welps':				{ 'reps_q4':  10 },
	'fight ghoul army':					{ 'reps_q1':   4 },
	'fight gildamesh':					{ 'reps_q3':  32 },
	'fight ice beast':					{ 'reps_q3':  40 },
	'fight infested soldiers':			{ 'reps_q6':  25 },
	'fight off demons':					{ 'reps_q5':  21 },
	'fight off zombie infestation':		{ 'reps_d3':  12 },
	'fight snow king':					{ 'reps_q3':  24 },
	'fight the guardians':				{ 'reps_q16':  0 },
	'fight the half-giant sephor':		{ 'reps_q4':   9 },
	'fight time elementals':			{ 'reps_q16':  0 },
	'fight treants':					{ 'reps_q2':  27 },
	'fight undead zombies':				{ 'reps_q2':  16 },
	'fight water demon lord':			{ 'reps_q2':  31 },
	'fight water demons':				{ 'reps_q2':  30 },
	'fight water spirits':				{ 'reps_q2':  40 },
	'final preparations':				{ 'reps_q15':  0 },
	'find a way across':				{ 'reps_q13':  0 },
	'find answers':						{ 'reps_q12':  0 },
	'find crypt key':					{ 'reps_q15':  0 },
	'find escape route':				{ 'reps_q12':  0 },
	'find evidence of dragon attack':	{ 'reps_d2':   8 },
	'find hidden path':					{ 'reps_d2':  10 },
	'find nezeals keep':				{ 'reps_d3':  12 },
	'find prison key':					{ 'reps_q12':  0 },
	'find rock worms weakness':			{ 'reps_d2':  10 },
	'find runes':						{ 'reps_q15':  0 },
	'find shelter from haze':			{ 'reps_q13':  0 },
	'find shortcut':					{ 'reps_q14':  0 },
	'find source of the attacks':		{ 'reps_d3':  12 },
	'find supplies':					{ 'reps_q14':  0 },
	'find survivors':					{ 'reps_q8':  14 },
	'find the dark elves':				{ 'reps_d1':  12 },
	'find the demonic army':			{ 'reps_d1':  12 },
	'find the druids':					{ 'reps_d4':  12 },
	'find the entrance':				{ 'reps_q8':  14 },
	'find the exit':					{ 'reps_q9':  17 },
	'find the safest path':				{ 'reps_q10': 14 },
	'find the source of corruption':	{ 'reps_d4':  12 },
	'find the woman? father':			{ 'reps_d5':  12 },
	'find time key':					{ 'reps_q16':  0 },
	'find time runes':					{ 'reps_q16':  0 },
	'find troll weakness':				{ 'reps_q2':  10 },
	'find way across':					{ 'reps_q16':  0 },
	'find your way out':				{ 'reps_q7':  15 },
	'fire and brimstone':				{ 'reps_q7':  12 },
	'forest of ash':					{ 'reps_d4':  11 },
	'fortress':							{ 'reps_a2':   8 },
	'freeing arielle':					{ 'reps_q12': 10 },
	'furest hellblade':					{ 'reps_d3':  17 },
	'gain access':						{ 'reps_q10':  0 },
	'gain entry':						{ 'reps_q11': 17 },
	'gates to the undead':				{ 'reps_q6':  17 },
	'gateway':							{ 'reps_q8':  11 },
	'gather crystals':					{ 'reps_q15':  0 },
	'gather earth essence':				{ 'reps_q13':  0 },
	'gather life dust':					{ 'reps_q13':  0 },
	'gather nature essence':			{ 'reps_q13':  0 },
	'gather samples':					{ 'reps_q13':  0 },
	'gather supplies':					{ 'reps_q12':  0, 'reps_q13':  0 },
	'get information from the druid':	{ 'reps_d4':  12 },
	'get water for the druid':			{ 'reps_d4':  12 },
	'grim outlook':						{ 'reps_q9':  17 },
	'guard against attack':				{ 'reps_d5':  12 },
	'hakkal woods':						{ 'reps_q13':  7 },
	'heal arielle':						{ 'reps_q12':  0 },
	'heal wounds':						{ 'reps_q7':  20 },
	'heat the villagers':				{ 'reps_q1':   4 },
	'holy fire':						{ 'reps_d4':  11 },
	'hunt for food':					{ 'reps_q13':  0 },
	'iapetian gateway':					{ 'reps_q15':  0 },
	'impending battle':					{ 'reps_q10': 10 },
	'infiltrate trakan':				{ 'reps_q12':  0 },
	'inspire soldiers':					{ 'reps_q12':  0 },
	'interrogate the prisoners':		{ 'reps_q9':  17 },
	'investigate temple':				{ 'reps_q13':  0 },
	'investigate the gateway':			{ 'reps_q8':  14 },
	'inviting vengeance':				{ 'reps_q16': 11 },
	'ironfist dwarves':					{ 'reps_q10': 10 },
	'join army':						{ 'reps_q15':  0 },
	'join up with artanis':				{ 'reps_d1':  12 },
	'judgement stronghold':				{ 'reps_q8':  11 },
	'juliean desert':					{ 'reps_q11': 12 },
	'karth':							{ 'reps_q14': 14 },
	'kelp forest':						{ 'reps_a1':  20 },
	'kill diseased treants':			{ 'reps_q13':  0 },
	'kill gildamesh':					{ 'reps_q3':  34 },
	'kill river hydras':				{ 'reps_q14':  0 },
	'kill shades':						{ 'reps_q12':  0 },
	'kill slimes':						{ 'reps_q13':  0 },
	'kill vampire bats':				{ 'reps_d3':  10 },
	'koralan coast town':				{ 'reps_q11': 14 },
	'koralan townspeople':				{ 'reps_q11': 10 },
	'lands end':						{ 'reps_q16':  0 },
	'last trial':						{ 'reps_q16':  0 },
	'learn about death knights':		{ 'reps_d5':  12 },
	'learn aurelius intentions':		{ 'reps_q11':  0 },
	'learn counterspell':				{ 'reps_d1':  12 },
	'learn holy fire':					{ 'reps_d4':  12 },
	'lonely journey':					{ 'reps_q15': 11 },
	'look for clues':					{ 'reps_q8':  14 },
	'lothar the ranger':				{ 'reps_q12':  9 },
	'make camp':						{ 'reps_q13':  0, 'reps_q14':  0 },
	'make leap of faith':				{ 'reps_q16':  0 },
	'make preparations':				{ 'reps_q14':  0 },
	'marauders!':						{ 'reps_d5':   9 },
	'march into the undead lands':		{ 'reps_q6':  24 },
	'march to the unholy war':			{ 'reps_q6':  25 },
	'mausoleum of triste':				{ 'reps_q3':  17 },
	'misty hills of boralis':			{ 'reps_q3':  20 },
	'mount aretop':						{ 'reps_d2':  25 },
	'move supplies':					{ 'reps_q14':  0 },
	'navigate passage':					{ 'reps_q15':  0 },
	'navigate the labryrinth':			{ 'reps_q16':  0 },
	'navigate the waters':				{ 'reps_q16':  0 },
	'nightfall':						{ 'reps_q12':  9 },
	'nightmare':						{ 'reps_q6':  20 },
	'nighttime infiltration':			{ 'reps_q14': 13 },
	'open portal':						{ 'reps_q15':  0 },
	'open the shadowgates':				{ 'reps_q16':  0 },
	'outmaneuver lothar':				{ 'reps_q12':  0 },
	'outpost entrance':					{ 'reps_q11': 12 },
	'path':								{ 'reps_a2':   0 },
	'path to heaven':					{ 'reps_q8':  11 },
	'perform time alchemy':				{ 'reps_q16':  0 },
	'persuade terra':					{ 'reps_q12':  0 },
	'pick up the orc trail':			{ 'reps_q1':   5 },
	'plan strategy':					{ 'reps_q14':  0 },
	'plan the attack':					{ 'reps_d5':  12 },
	'portal of atlantis':				{ 'reps_a1':  20 },
	'power of excalibur':				{ 'reps_q8':  11 },
	'prepare for ambush':				{ 'reps_q1':   5 },
	'prepare for battle':				{ 'reps_d2':  12, 'reps_q5':  21 },
	'prepare for dark':					{ 'reps_q13':  0 },
	'prepare for journey':				{ 'reps_q15':  0, 'reps_q16':  0 },
	'prepare for the trials':			{ 'reps_q9':  17 },
	'prepare for war':					{ 'reps_q14':  0, 'reps_q15':  0 },
	'prepare tactics':					{ 'reps_q10':  0 },
	'prepare troops':					{ 'reps_q10':  0 },
	'prevent dragon? escape':			{ 'reps_d2':  12 },
	'protect temple from raiders':		{ 'reps_q2':  40 },
	'purge forest of evil':				{ 'reps_q2':  27 },
	'pursuing orcs':					{ 'reps_q1':   6 },
	'put out the fires':				{ 'reps_d2':   8 },
	'question dark elf prisoners':		{ 'reps_d1':  12 },
	'question the druidic wolf':		{ 'reps_d4':  12 },
	'question townspeople':				{ 'reps_q11': 17 },
	'question vulcan':					{ 'reps_q8':  14 },
	'ready defenses':					{ 'reps_q12':  0 },
	'ready soldiers':					{ 'reps_q12':  0 },
	'ready the horses':					{ 'reps_q1':   5 },
	'reason with guards':				{ 'reps_q12':  0 },
	'recover the key':					{ 'reps_q9':  17 },
	'recruit allies':					{ 'reps_q10':  0 },
	'recruit elekin to join you':		{ 'reps_d2':   9 },
	'recruit furest to join you':		{ 'reps_d3':  12 },
	'recruit guide':					{ 'reps_q15':  0 },
	'redeemers message':				{ 'reps_q16':  0 },
	'regain strength':					{ 'reps_q15':  0 },
	'repair bridge':					{ 'reps_q13':  0 },
	'repel gargoyle raid':				{ 'reps_q4':  14 },
	'request council':					{ 'reps_q10':  0 },
	'request entrance':					{ 'reps_q12':  0 },
	'rescue survivors':					{ 'reps_q8':  14 },
	'resist the lost souls':			{ 'reps_q5':  25 },
	'retrieve dragon slayer':			{ 'reps_d2':  10 },
	'retrieve the jeweled heart':		{ 'reps_d5':  12 },
	'ride down':						{ 'reps_q14':  0 },
	'ride to aretop':					{ 'reps_d2':  12 },
	'ride towards the palace':			{ 'reps_q9':  17 },
	'river of lava':					{ 'reps_q10': 10 },
	'river of light':					{ 'reps_q1':   5, 'reps_q14': 13 },
	'save dying creatures':				{ 'reps_q12':  0 },
	'save lost souls':					{ 'reps_q5':  24 },
	'save stranded soldiers':			{ 'reps_q10': 15 },
	'scale the cliffs':					{ 'reps_q16':  0 },
	'scout karth':						{ 'reps_q14':  0 },
	'seek out elekin':					{ 'reps_d2':   9 },
	'seek out furest hellblade':		{ 'reps_d3':  12 },
	'seek out jeweled heart':			{ 'reps_d5':  12 },
	'setup siege':						{ 'reps_q14':  0 },
	'shadowspire':						{ 'reps_q16':  0 },
	'shield of the stars':				{ 'reps_d3':  20 },
	'siege on the capital':				{ 'reps_q14':  0 },
	'signs of the scourge':				{ 'reps_q13':  9 },
	'slaughter orcs':					{ 'reps_q3':  15 },
	'slay cave bats':					{ 'reps_d2':  10 },
	'slay the black dragons':			{ 'reps_q5':  32 },
	'slay the guardian':				{ 'reps_q9':  17 },
	'slay the sea serpent':				{ 'reps_d5':  12 },
	'sneak attack on dragon':			{ 'reps_d2':  12 },
	'sneak into the city':				{ 'reps_q8':  14 },
	'sneak up on orcs':					{ 'reps_q1':   6 },
	'soldiers of the black lion':		{ 'reps_d5':  10 },
	'solitude lair':					{ 'reps_q16':  0 },
	'spire of death':					{ 'reps_q5':  20 },
	'sporeguard forest':				{ 'reps_q12': 10 },
	'sporeguard revisited':				{ 'reps_q13':  8 },
	'spring surprise attack':			{ 'reps_d5':  12 },
	'stall for time':					{ 'reps_q12':  0 },
	'stave off evil':					{ 'reps_q15':  0 },
	'stop the wolf from channeling':	{ 'reps_d4':  12 },
	'storm the castle':					{ 'reps_d5':  12 },
	'storm the ivory palace':			{ 'reps_q9':  17 },
	'sulfurous springs':				{ 'reps_q11': 10 },
	'summon legendary defenders':		{ 'reps_q6':  25 },
	'summon shadowpatj':				{ 'reps_q16':  0 },
	'surround rebels':					{ 'reps_q10':  0 },
	'survey area':						{ 'reps_q13':  0 },
	'survey battlefield':				{ 'reps_q10':  0 },
	'survey landscape':					{ 'reps_q15':  0 },
	'survey the cliffs':				{ 'reps_q16':  0 },
	'survey the surroundings':			{ 'reps_q8':  14 },
	'survive the storm':				{ 'reps_q11':  0 },
	'survive troll ambush':				{ 'reps_q2':  10 },
	'surviving the onslaught':			{ 'reps_q9':  17 },
	'swim ashore':						{ 'reps_q16':  0 },
	'taubourne falls':					{ 'reps_q13': 10 },
	'tenvir summit':					{ 'reps_q13': 12 },
	'test her power':					{ 'reps_q14':  0 },
	'tezzari village':					{ 'reps_q12': 12 },
	'the belly of the demon':			{ 'reps_q5':  16 },
	'the betrayed lands':				{ 'reps_q4':  16 },
	'the black portal':					{ 'reps_d1':  15 },
	'the cave of wonder':				{ 'reps_q3':  20 },
	'the citadel':						{ 'reps_q15':  0 },
	'the crystal caverns':				{ 'reps_d2':  11 },
	'the dark labyrinth':				{ 'reps_q16':  0 },
	'the darkening skies':				{ 'reps_q9':  17 },
	'the dead forests':					{ 'reps_q12': 11 },
	'the deep':							{ 'reps_a1':  20 },
	'the elven sorceress':				{ 'reps_d1':  11 },
	'the fallen druids':				{ 'reps_d4':  12 },
	'the final march':					{ 'reps_q15':  0 },
	'the final stretch':				{ 'reps_q9':  17 },
	'the forbidden forest':				{ 'reps_q2':  20 },
	'the forbidden ritual':				{ 'reps_q5':  20 },
	'the gateway':						{ 'reps_q12': 10 },
	'the green haze':					{ 'reps_q13': 10 },
	'the hidden lair':					{ 'reps_d1':  13 },
	'the hollowing moon':				{ 'reps_q6':  17 },
	'the infestation of winterguard':	{ 'reps_d3':  10 },
	'the invasion':						{ 'reps_q8':  11 },
	'the keep of corelan':				{ 'reps_q3':  17 },
	'the keep of isles':				{ 'reps_q4':  16 },
	'the kingdom of alarean':			{ 'reps_d5':  15 },
	'the last gateway':					{ 'reps_q9':  17 },
	"the lich ne'zeal":					{ 'reps_d3':  13 },
	"the lich's keep":					{ 'reps_d3':  15 },
	'the life altar':					{ 'reps_q13':  7 },
	'the life temple':					{ 'reps_q13':  8 },
	'the living gates':					{ 'reps_q5':  20 },
	'the long path':					{ 'reps_q7':  12 },
	'the outlook':						{ 'reps_q15':  0 },
	'the peaks of draneth':				{ 'reps_d5':  21 },
	'the poison source':				{ 'reps_q11':  0 },
	'the rebellion':					{ 'reps_q10': 10 },
	'the redeemer':						{ 'reps_q15':  0 },
	'the return home':					{ 'reps_q8':  11 },
	'the return of the dragon':			{ 'reps_d2':   9 },
	'the ride south':					{ 'reps_q8':  14 },
	'the river crossing':				{ 'reps_q16':  0 },
	'the river of blood':				{ 'reps_q5':  20 },
	'the scourge':						{ 'reps_q12':  8 },
	'the sea temple':					{ 'reps_a1':  20 },
	'the search for clues':				{ 'reps_d1':  12 },
	'the second temple of water':		{ 'reps_q4':  25 },
	'the smouldering pit':				{ 'reps_q4':  40 },
	'the source of darkness':			{ 'reps_d1':  20 },
	'the source of magic':				{ 'reps_d4':  15 },
	'the southern entrance':			{ 'reps_q12':  9 },
	'the stairs of terra':				{ 'reps_q2':  10 },
	'the stone lake':					{ 'reps_q1':   5 },
	'the sunken city':					{ 'reps_d5':  17 },
	'the tree of life':					{ 'reps_d4':  21 },
	'the vanguard of destruction':		{ 'reps_d1':  21 },
	'the water temple':					{ 'reps_q2':  17 },
	'til morning comes':				{ 'reps_q12': 13 },
	'towards rodinia':					{ 'reps_q15':  0 },
	'town':								{ 'reps_a2':   0 },
	'track down soldiers':				{ 'reps_d5':  12 },
	'track lothar':						{ 'reps_q12':  0 },
	'track sylvana':					{ 'reps_d1':  12 },
	'train with ambrosia':				{ 'reps_d1':  12 },
	'train with aurora':				{ 'reps_d4':  12 },
	'trakan prison':					{ 'reps_q12':  9 },
	'trakan sky bridge':				{ 'reps_q12': 11 },
	'trakan village':					{ 'reps_q12':  7 },
	'transport to iapetus':				{ 'reps_q15':  0 },
	'travel to the tree of life':		{ 'reps_d4':  12 },
	'travel to winterguard':			{ 'reps_d3':  12 },
	'triste':							{ 'reps_q3':  20 },
	'undead crusade':					{ 'reps_q6':  17 },
	'underground entrance':				{ 'reps_q15':  0 },
	'underground path':					{ 'reps_q12':  8 },
	'underwater':						{ 'reps_a2':   0 },
	'underwater ruins':					{ 'reps_a1':  20 },
	'unholy war':						{ 'reps_q6':  20 },
	'unlikely alliance':				{ 'reps_q14': 10 },
	'unlock altar':						{ 'reps_q13':  0 },
	'unlock gate':						{ 'reps_q15':  0 },
	'use artifact relic':				{ 'reps_q13':  0 },
	'use battering ram':				{ 'reps_q11':  0 },
	'vengeance':						{ 'reps_d2':  17 },
	'vesuv bridge':						{ 'reps_q10': 10 },
	'vesuv lookout':					{ 'reps_q2':  17 },
	'visit the blacksmith':				{ 'reps_q1':  20 },
	'vulcans secret':					{ 'reps_q8':  11 },
	'watch the skies':					{ 'reps_d3':  12 }
};

// vi: ts=4
